using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;
using BLL.GEN_BLL.TBL_RIGHTS_MAIN;
using BLL.GEN_BLL.TBL_RIGHTS_TEMPLATE;


namespace PRESENTATION_LAYER.GEN_PRESENTATION_LAYER.Forms.TBL_RIGHTS_MAIN
{
      public class cls_TBL_RIGHTS_MAIN_P
      {

            Boolean isAllowedInsertion = true, isAllowedUpdation = true, isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;

            GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;
            GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView ObjGenGrid;



            GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

            DATASET.GEN_DATASET.cls_DataSet obj_cls_DataSet_GEN = new DATASET.GEN_DATASET.cls_DataSet();

            GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

            BLL.GEN_BLL.TBL_RIGHTS_MAIN.cls_TBL_RIGHTS_MAIN obj_cls_TBL_RIGHTS_MAIN = new BLL.GEN_BLL.TBL_RIGHTS_MAIN.cls_TBL_RIGHTS_MAIN();

            frm_TBL_RIGHTS_MAIN obj_frm_TBL_RIGHTS_MAIN = null;

            DataTable dt_Datanavigator = new DataTable();
            DataTable DT_dataTableForGrid = new DataTable();

            DataTable dt_Visible_Rights_AssignedByParent_NotFixedByParent = new DataTable();
            DataTable dt_Visible_Rights_NotAssignedByParent_NotFixedByParent = new DataTable();
            DataTable dt_Value_Rights_NotFixedByParent = new DataTable();
            DataTable dt_Visible_Rights_FixedByParent = new DataTable();
            DataTable dt_Value_Rights_FixedByParent = new DataTable();
            DataTable dt_Visible_Value_Rights_FixedByGrandParents = new DataTable();



            void InitializeComponents(frm_TBL_RIGHTS_MAIN pobj_frm_TBL_RIGHTS_MAIN, String pID, String pRIGHTS_MAIN_rightAssigner)
            {

                  obj_frm_TBL_RIGHTS_MAIN = pobj_frm_TBL_RIGHTS_MAIN;
                  GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_RIGHTS_MAIN, 'A');
                  obj_cls_TBL_RIGHTS_MAIN.obj_XtraForm = pobj_frm_TBL_RIGHTS_MAIN;

                  if (!obj_cls_TBL_RIGHTS_MAIN.Open())
                        obj_frm_TBL_RIGHTS_MAIN.Close();



                  if (pID == "N")
                        Referesh("True");
                  else
                  {
                        obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.Text = pID;

                        selection("Load All Rights To Assign To Child Or Sibling", pID, pRIGHTS_MAIN_rightAssigner,false);

                  }

            }


            public cls_TBL_RIGHTS_MAIN_P(frm_TBL_RIGHTS_MAIN pobj_frm_TBL_RIGHTS_MAIN, String pID, string pRIGHTS_MAIN_rightAssigner, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView pObjGenGrid, bool pIs_DisturbanceOnce)//VVVParamVVV
            {
                  ObjGenForm = pObjGenForm;
                  ObjGenGrid = pObjGenGrid;
                  isDisturebedOnce = pIs_DisturbanceOnce;
                  InitializeComponents(pobj_frm_TBL_RIGHTS_MAIN, pID, pRIGHTS_MAIN_rightAssigner);

            }


            public bool validate(out string value, bool pIs_Delete)
            {
                  if (pIs_Delete)
                  {

                        if (!isAllowedDeletion)
                        {
                              value = obj_cls_MessageBox.error_delete_rights;
                              return false;

                        }

                        if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'I')
                        {
                              value = obj_cls_MessageBox.error_selection_msg;
                              return false;
                        }

                  }
                  else
                  {
                        if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'I')
                        {
                              if (!isAllowedInsertion)
                              {
                                    value = obj_cls_MessageBox.error_insert_rights;
                                    return false;

                              }

                        }
                        if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'U')
                        {
                              if (!isAllowedUpdation)
                              {
                                    value = obj_cls_MessageBox.error_update_rights;
                                    return false;

                              }

                        }

                        if (!combineAlltheRowsRecursiveParent())
                        {
                              value = "V_P";
                              return false;
                        }


                  }

                  if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'U')
                        if (Convert.ToString(obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }
                  if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'I')
                        if (!obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }


                  value = "N";
                  return true;
            }




            public void getMax()
            {
                  if (obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                  {

                        int tempID = obj_cls_DataSet_GEN.f_GETMAX("TBL_RIGHTS_MAIN", 0, 0, 0, "", "", "");
                        obj_frm_TBL_RIGHTS_MAIN.maxID = tempID.ToString();
                        obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.Text = obj_frm_TBL_RIGHTS_MAIN.maxID;

                  }
            }



            public void loadGridLookUpEdit(string Status)
            {



            }

            public string valueGetting(bool pIs_Delete)
            {

                  try
                  {

                        string validate_value = "";

                        if (!validate(out validate_value, pIs_Delete))
                        {

                              if (validate_value == "N")
                                    return "V_P";
                              else
                                    return validate_value;

                        }

                        if (pIs_Delete)
                        {
                              obj_cls_TBL_RIGHTS_MAIN.STATUS = "D";
                              obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_ID = Convert.ToString(obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.EditValue);
                        }
                        {
                              obj_cls_TBL_RIGHTS_MAIN.dt_Detail = DT_dataTableForGrid;
                              obj_cls_TBL_RIGHTS_MAIN.Is_Auto_Generated = obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Checked;

                              if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'I')
                              {

                                    if (!obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                                          obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_ID = Convert.ToString(obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.EditValue);
                              }
                              else
                                    obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_ID = Convert.ToString(obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.EditValue);


                              obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_rightAssigner = GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID;
                              obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_name = obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_name.EditValue.ToString().Trim();


                        }



                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }
            public string valueSetting(DataSet ds)
            {

                  try
                  {

                        DataTable dt_Main = ds.Tables[0];
                        DT_dataTableForGrid = ds.Tables[1].Copy();
                        initiateTreeForValueBaseRights();
                        //initiateGrid(false);
                        obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                        obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_name.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_RIGHTS_MAIN.cls_CTBL_RIGHTS_MAIN.RIGHTS_MAIN_name];

                        obj_frm_TBL_RIGHTS_MAIN.DBStatus = 'U';
                        obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = false;
                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }


            public void Referesh(String isComplete)
            {

                  if (isComplete == "True")
                  {

                        //try
                        //{
                        //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                        //    foreach (DataRow d in drr)
                        //    {
                        //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedDeletion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedInsertion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedUpdation = true;
                        //        }
                        //    }

                        //}
                        //catch (Exception ex)
                        //{
                        //    //throw;
                        //}




                        obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                        if (!isAllowedInsertion && !isAllowedUpdation)
                              obj_frm_TBL_RIGHTS_MAIN.SimpleButton_Save.Enabled = false;
                        if (!isAllowedDeletion)
                              obj_frm_TBL_RIGHTS_MAIN.SimpleButton_Delete.Enabled = false;
                        //initiateGrid(true);
                        //initiateTreeForValueBaseRights();
                        
                        selection("N", GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID, GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID_RIGHTS_MAIN_rightAssigner,false);
                       // selection("N", GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID, GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID_RIGHTS_MAIN_rightAssigner, false);
                      
                        Referesh("False");

                  }
                  else if (isComplete == "Partial")
                  {
                        selection("N", GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID, GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID_RIGHTS_MAIN_rightAssigner,false);
                        Referesh("False");

                  }


                  ObjGenForm.GenRefresh();
                  obj_frm_TBL_RIGHTS_MAIN.DBStatus = 'I';
                  obj_frm_TBL_RIGHTS_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = true;
                  //obj_frm_TBL_RIGHTS_MAIN.CheckEdit_navigate.Checked = false;
                  getMax();
                  DT_dataTableForGrid.Rows.Clear();

            }

            public void Delete()
            {

                  string executeFunctions = valueGetting(true);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }


                  if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
                  {

                        return;

                  }





                  obj_cls_TBL_RIGHTS_MAIN.RIGHTS_MAIN_ID = obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.Text;

                  if (obj_cls_TBL_RIGHTS_MAIN.deletion())
                  {
                        Referesh("Partial");
                        if (isDisturebedOnce)
                              obj_frm_TBL_RIGHTS_MAIN.Close();
                  }

            }

            public void Save()
            {


                  string executeFunctions = valueGetting(false);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }

                  if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'I')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                        {
                              return;
                        }

                        if (obj_cls_TBL_RIGHTS_MAIN.insertionUpdation('I'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_RIGHTS_MAIN.Close();
                        }


                  }

                  else if (obj_frm_TBL_RIGHTS_MAIN.DBStatus == 'U')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                        {
                              return;
                        }

                        if (obj_cls_TBL_RIGHTS_MAIN.insertionUpdation('U'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_RIGHTS_MAIN.Close();
                        }
                  }

            }

            public void selection(string pStatus, string pRIGHTS_MAIN_ID, string pRIGHTS_MAIN_rightAssigner,bool pIsReferesh)
            {

                  if (pStatus == "Load All Rights To Assign To Child Or Sibling")
                  {
                        string executeFunctions = "";
                        obj_cls_DataSet_GEN.f_TBL_RIGHTS_MAIN(pStatus, pRIGHTS_MAIN_ID, pRIGHTS_MAIN_rightAssigner);
                              DataSet ds = obj_cls_DataSet_GEN.g_TBL_RIGHTS_MAIN;
                              if (ds == null)
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                                    Referesh("False");
                                    return;

                              }

                              
                              if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                              {
                                    
                              }
                              else
                              {

                                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                                    Referesh("False");
                                    return;

                              }

                              dt_Visible_Rights_AssignedByParent_NotFixedByParent    = ds.Tables[0].Copy();
                              dt_Visible_Rights_NotAssignedByParent_NotFixedByParent = ds.Tables[1].Copy();
                              dt_Value_Rights_NotFixedByParent = ds.Tables[2].Copy();
                              dt_Visible_Rights_FixedByParent = ds.Tables[3].Copy();
                              dt_Value_Rights_FixedByParent = ds.Tables[4].Copy();
                              dt_Visible_Value_Rights_FixedByGrandParents = ds.Tables[5].Copy();
                              DT_dataTableForGrid = ds.Tables[5].Clone();

                              initiateTreeForValueBaseRights();
                              initiateTreeForVisibleBaseRights();

                        if(!pIsReferesh)
                              executeFunctions = valueSetting(ds);
                       
                  }

                  else if (pStatus == "N")
                  {
                        //if (pRIGHTS_MAIN_ID == "")
                        //{
                              obj_cls_DataSet_GEN.f_TBL_RIGHTS_MAIN("L", pRIGHTS_MAIN_ID, pRIGHTS_MAIN_rightAssigner);
                              DataSet ds = obj_cls_DataSet_GEN.g_TBL_RIGHTS_MAIN;
                              if (ds == null)
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                                    Referesh("False");
                                    return;

                              }

                              dt_Datanavigator = ds.Tables[0].Copy();
                              obj_frm_TBL_RIGHTS_MAIN.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                        //}
                        //else
                        //{

                              //pRIGHTS_MAIN_ID = dt_Datanavigator.Rows[Convert.ToInt32(pRIGHTS_MAIN_ID)][cls_CTBL_RIGHTS_MAIN.priRIGHTS_MAIN_ID].ToString();
                              selection("Load All Rights To Assign To Child Or Sibling", pRIGHTS_MAIN_ID, pRIGHTS_MAIN_rightAssigner,true);
                        //}

                        selection("Load All Rights To Assign To Child Or Sibling", pRIGHTS_MAIN_ID, pRIGHTS_MAIN_rightAssigner,false);
                  }
                  else if (pStatus == "A")
                  {

                        obj_cls_DataSet_GEN.f_TBL_RIGHTS_MAIN("A", GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID, GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID);
                        DataSet ds = obj_cls_DataSet_GEN.g_TBL_RIGHTS_MAIN;

                        if (ds == null)
                        {
                              obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                              Referesh("False");
                              return;

                        }


                        obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150", 1);
                        obj_frlLOOKUP.ShowDialog();
                        string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                        if (value != "")
                        {
                              string[] cols_values = value.Split('|');
                              obj_frm_TBL_RIGHTS_MAIN.CheckEdit_navigate.Checked = false;
                              selection("Load All Rights To Assign To Child Or Sibling", cols_values[0], GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID,true);
                        }

                  }
                 
                  else
                  {

                        //obj_frm_TBL_RIGHTS_MAIN.maxID = obj_frm_TBL_RIGHTS_MAIN.TextEdit_RIGHTS_MAIN_ID.Text = pId;
                        //obj_cls_DataSet_GEN.f_TBL_RIGHTS_MAIN("V", pId, GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_RightID);
                        //DataSet ds = obj_cls_DataSet_GEN.g_TBL_RIGHTS_MAIN;
                        //string executeFunctions = "";

                        //if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                        //{
                        //      executeFunctions = valueSetting(ds);
                        //}
                        //else
                        //{

                        //      obj_cls_MessageBox.MessageBoxStatic("TB_E");
                        //      Referesh("False");
                        //      return;

                        //}


                        //if (executeFunctions != "ok")
                        //{
                        //      obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                        //      return;

                        //      Referesh("False");


                        //}


                  }

            }

            void initiateTreeForValueBaseRights()
            {
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_valueBase.DataSource = dt_Value_Rights_NotFixedByParent;

                  obj_frm_TBL_RIGHTS_MAIN.TreeList_valueBase.ParentFieldName = cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey;
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_valueBase.KeyFieldName = cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey;
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_valueBase.PopulateColumns();
                  

                  //objfrm_COA.TL_COA.OptionsBehavior.AllowExpandOnDblClick = true;

            }
            void initiateTreeForVisibleBaseRights()
            {
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.DataSource = dt_Visible_Rights_AssignedByParent_NotFixedByParent;

                  obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.ParentFieldName = cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey;
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.KeyFieldName = cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey;
                  obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.PopulateColumns();


                  //objfrm_COA.TL_COA.OptionsBehavior.AllowExpandOnDblClick = true;

            }


            public void initiateGrid()
            {
                  



                  //obj_frm_TBL_RIGHTS_MAIN.GridControl_TBL_RIGHTS_DETAILS.DataSource = DT_dataTableForGrid;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.PopulateColumns();

                  ////GEN.GEN_GEN.GenericClasses.Grid.cls_GridAppearance.setAppearance(obj_frm_TBL_TEMP_MAIN.GridView_TBL_TEMP_DET, "I");

                  //// RIGHTS_DETAILS_parentKey

                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey].Caption = "RIGHTS_DETAILS_parentKey";
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey].OptionsColumn.FixedWidth = true;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey].Width = 100;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_parentKey].Tag = "N|N|N|N";


                  //// RIGHTS_DETAILS_primaryKey

                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey].Caption = "RIGHTS_DETAILS_primaryKey";
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey].OptionsColumn.FixedWidth = true;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey].Width = 100;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_primaryKey].Tag = "N|N|N|N";


                  //// RIGHTS_DETAILS_isFixed

                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_isFixed].Caption = "Is Fixed";
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_isFixed].OptionsColumn.FixedWidth = true;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_isFixed].Width = 100;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_isFixed].Tag = "N|N|N|N";


                  //// RIGHTS_DETAILS_Value

                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_Value].Caption = "Value";
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_Value].OptionsColumn.FixedWidth = true;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_Value].Width = 100;
                  //obj_frm_TBL_RIGHTS_MAIN.GridView_TBL_RIGHTS_DETAILS.Columns[cls_CTBL_RIGHTS_MAIN.RIGHTS_DETAILS_Value].Tag = "N|N|N|N";






                  ObjGenGrid.Formatting();
            }



            bool combineAlltheRowsRecursiveParent()
            {
                  try
                  {

                        foreach (DataRow tmpDataRow in dt_Value_Rights_NotFixedByParent.Rows)
                              DT_dataTableForGrid.ImportRow(tmpDataRow);

                        foreach (DataRow tmpDataRow in dt_Visible_Rights_FixedByParent.Rows)
                              DT_dataTableForGrid.ImportRow(tmpDataRow);

                        foreach (DataRow tmpDataRow in dt_Value_Rights_FixedByParent.Rows)
                              DT_dataTableForGrid.ImportRow(tmpDataRow);

                        foreach (DataRow tmpDataRow in dt_Visible_Value_Rights_FixedByGrandParents.Rows)
                              DT_dataTableForGrid.ImportRow(tmpDataRow);




                        //obj_frm_TBL_RIGHTS_MAIN.TreeList_valueBase.Nodes



                        foreach (DevExpress.XtraTreeList.Nodes.TreeListNode tmpTreeListNode in obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.Nodes)
                        {
                              if (tmpTreeListNode.CheckState == System.Windows.Forms.CheckState.Checked || tmpTreeListNode.CheckState == System.Windows.Forms.CheckState.Indeterminate)
                              {
                                    DataRowView tmpDataRowView = (DataRowView)obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.GetDataRecordByNode(tmpTreeListNode);
                                    DT_dataTableForGrid.ImportRow(tmpDataRowView.Row);
                                    if (combineAlltheRowsRecursiveChild(tmpTreeListNode))
                                          continue;
                              }
                        }


                  }
                  catch (Exception ex)
                  {
                        return false;
                  }

                  return true;

            }

            bool combineAlltheRowsRecursiveChild(DevExpress.XtraTreeList.Nodes.TreeListNode ptmpTreeListNode)
            {
                  try
                  {




                        foreach (DevExpress.XtraTreeList.Nodes.TreeListNode tmpTreeListNode in ptmpTreeListNode.Nodes)
                        {
                              if (tmpTreeListNode.CheckState == System.Windows.Forms.CheckState.Checked || tmpTreeListNode.CheckState == System.Windows.Forms.CheckState.Indeterminate)
                              {
                                    DataRowView tmpDataRowView = (DataRowView)obj_frm_TBL_RIGHTS_MAIN.TreeList_visibleBase.GetDataRecordByNode(tmpTreeListNode);
                                    DT_dataTableForGrid.ImportRow(tmpDataRowView.Row);
                              }
                        }


                  }
                  catch (Exception ex)
                  {
                        return false;
                  }

                  return true;

            }

            //VVVGRIDINFOVVV



      }
}
