using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;

namespace PRESENTATION_LAYER.GEN_PRESENTATION_LAYER.Forms.TBL_DEPARTMENTS
{
    public class cls_TBL_DEPARTMENTS_P
    {

        Boolean isAllowedInsertion = true, 
            isAllowedUpdation = true, 
            isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;

        GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;

        GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

        DATASET.IMS_DATASET.cls_DataSet obj_cls_DataSet_GEN = new DATASET.IMS_DATASET.cls_DataSet();

        GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

        BLL.IMS_BLL.TBL_DEPARTMENTS.cls_TBL_DEPARTMENTS obj_cls_TBL_DEPARTMENTS = new BLL.IMS_BLL.TBL_DEPARTMENTS.cls_TBL_DEPARTMENTS();

        frm_TBL_DEPARTMENTS obj_frm_TBL_DEPARTMENTS = null;

        DataTable dt_Datanavigator = new DataTable();

        void InitializeComponents(frm_TBL_DEPARTMENTS pobj_frm_TBL_DEPARTMENTS, String pID)
        {

            obj_frm_TBL_DEPARTMENTS = pobj_frm_TBL_DEPARTMENTS;
            GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_DEPARTMENTS, 'A');
            obj_cls_TBL_DEPARTMENTS.obj_XtraForm = pobj_frm_TBL_DEPARTMENTS;

            if (!obj_cls_TBL_DEPARTMENTS.Open())
                obj_frm_TBL_DEPARTMENTS.Close();



            if (pID == "N")
                Referesh("True");
            else
            {
                obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.Text = pID;

                selection("V", obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.Text.Trim());

            }

        }


        public cls_TBL_DEPARTMENTS_P(frm_TBL_DEPARTMENTS pobj_frm_TBL_DEPARTMENTS, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, bool pIs_DisturbanceOnce)//VVVParamVVV
        {
            ObjGenForm = pObjGenForm;
            isDisturebedOnce = pIs_DisturbanceOnce;
            InitializeComponents(pobj_frm_TBL_DEPARTMENTS, pID);

        }


        public bool validate(out string value, bool pIs_Delete)
        {
            if (pIs_Delete)
            {

                if (!isAllowedDeletion)
                {
                    value = obj_cls_MessageBox.error_delete_rights;
                    return false;

                }

                if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'I')
                {
                    value = obj_cls_MessageBox.error_selection_msg;
                    return false;
                }

            }
            else
            {
                if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'I')
                {
                    if (!isAllowedInsertion)
                    {
                        value = obj_cls_MessageBox.error_insert_rights;
                        return false;

                    }

                }
                if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'U')
                {
                    if (!isAllowedUpdation)
                    {
                        value = obj_cls_MessageBox.error_update_rights;
                        return false;

                    }

                }

                if (Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_name.EditValue) == "")
                {
                     value = obj_cls_MessageBox.error_Name_msg;
                    obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_name.Focus();
                    obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_name.Properties.AppearanceFocused.BorderColor = System.Drawing.Color.Red;
                    return false;
                }
                if (Convert.ToString(obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID.EditValue) == "" && obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_isParent.Checked)
                {
                      value = "V_P";
                      obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID.Focus();
                      obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID.Properties.AppearanceFocused.BorderColor = System.Drawing.Color.Red;
                      return false;
                }
            }

            if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'U')
                if (Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }
            if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'I')
                if (!obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }


            value = "N";
            return true;
        }




        public void getMax()
        {
            if (obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Checked)
            {

                int tempID = obj_cls_DataSet_GEN.f_GETMAX("TBL_DEPARTMENTS", 0, 0, 0, "", "", "");
                obj_frm_TBL_DEPARTMENTS.maxID = tempID.ToString();
                obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.Text = obj_frm_TBL_DEPARTMENTS.maxID;

            }
        }



        public void loadGridLookUpEdit(string Status)
        {
              if (Status == "TBL_DEPARTMENTS")
                    IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_DEPARTMENTSParent(obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID,false);
              
        }

        public string valueGetting(bool pIs_Delete)
        {

            try
            {

                string validate_value = "";

                if (!validate(out validate_value, pIs_Delete))
                {

                    if (validate_value == "N")
                        return "V_P";
                    else
                        return validate_value;

                }

                if (pIs_Delete)
                {
                    obj_cls_TBL_DEPARTMENTS.STATUS = "D";
                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_ID = Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.EditValue);
                }
                {

                    obj_cls_TBL_DEPARTMENTS.Is_Auto_Generated = obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Checked;

                    if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'I')
                    {

                        if (!obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Checked)
                            obj_cls_TBL_DEPARTMENTS.DEPARTMENT_ID = Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.EditValue);
                    }
                    else
                        obj_cls_TBL_DEPARTMENTS.DEPARTMENT_ID = Convert.ToString(obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.EditValue);


                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_name = obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_name.EditValue.ToString().Trim();
                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_narration = obj_frm_TBL_DEPARTMENTS.MemoEdit_DEPARTMENT_narration.EditValue.ToString().Trim();

                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_parentID = obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_isParent.Checked ? obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID.EditValue.ToString() : "N";
                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_isParent = !obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_isParent.Checked;
                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_stockLevel = obj_frm_TBL_DEPARTMENTS.ComboBoxEdit_Stocklevel.SelectedIndex +1;
                    obj_cls_TBL_DEPARTMENTS.DEPARTMENT_stockInLtr = obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_stockIsLtr.Checked;



                }



            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }

       

        public string valueSetting(DataSet ds)
        {

            try
            {

                DataTable dt_Main = ds.Tables[0];

                obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_name.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_name];
                obj_frm_TBL_DEPARTMENTS.MemoEdit_DEPARTMENT_narration.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_narration];
                obj_cls_TBL_DEPARTMENTS.DEPARTMENT_COA = dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_COA].ToString();
                obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_isParent.EditValue = !(bool)dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_isParent];

                if (obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_isParent.Checked)
                      obj_frm_TBL_DEPARTMENTS.GridLookUpEdit_DEPARTMENT_parentID.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_parentID].ToString(); ;
                obj_frm_TBL_DEPARTMENTS.ComboBoxEdit_Stocklevel.SelectedIndex = Convert.ToInt16( dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_stockLevel].ToString()) - 1;
                obj_frm_TBL_DEPARTMENTS.checkEdit_DEPARTMENT_stockIsLtr.Checked = (bool)dt_Main.Rows[0][BLL.IMS_BLL.TBL_DEPARTMENTS.cls_CTBL_DEPARTMENTS.DEPARTMENT_stockInLtr];

                  
                obj_frm_TBL_DEPARTMENTS.DBStatus = 'U';
                obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Enabled = false;
            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }


        public void Referesh(String isComplete)
        {

            if (isComplete == "True")
            {

                //try
                //{
                //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                //    foreach (DataRow d in drr)
                //    {
                //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                //        {
                //            isAllowedDeletion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                //        {
                //            isAllowedInsertion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                //        {
                //            isAllowedUpdation = true;
                //        }
                //    }

                //}
                //catch (Exception ex)
                //{
                //    //throw;
                //}




                obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                if (!isAllowedInsertion && !isAllowedUpdation)
                    obj_frm_TBL_DEPARTMENTS.SimpleButton_Save.Enabled = false;
                if (!isAllowedDeletion)
                    obj_frm_TBL_DEPARTMENTS.SimpleButton_Delete.Enabled = false;

                selection("N", "");
                Referesh("False");

            }
            else if (isComplete == "Partial")
            {
                selection("N", "");
                Referesh("False");

            }


            ObjGenForm.GenRefresh();
            obj_frm_TBL_DEPARTMENTS.DBStatus = 'I';
            obj_frm_TBL_DEPARTMENTS.CheckEdit_Is_AutoGenegereted.Enabled = true;
            //obj_frm_TBL_DEPARTMENTS.CheckEdit_navigate.Checked = false;
            getMax();
            loadGridLookUpEdit("TBL_DEPARTMENTS");


        }

        public void Delete()
        {

            string executeFunctions = valueGetting(true);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }


            if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
            {

                return;

            }





            obj_cls_TBL_DEPARTMENTS.DEPARTMENT_ID = obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.Text;

            if (obj_cls_TBL_DEPARTMENTS.deletion())
            {
                Referesh("Partial");
                if (isDisturebedOnce)
                    obj_frm_TBL_DEPARTMENTS.Close();
            }

        }

        public void Save()
        {


            string executeFunctions = valueGetting(false);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }

            if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'I')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_DEPARTMENTS.insertionUpdation('I'))
                {
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_DEPARTMENTS.Close();
                }


            }

            else if (obj_frm_TBL_DEPARTMENTS.DBStatus == 'U')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_DEPARTMENTS.insertionUpdation('U'))
                {
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_DEPARTMENTS.Close();
                }
            }

        }

        public void selection(string pStatus, string pId)
        {

            if (pStatus == "N")
            {
                if (pId == "")
                {
                      obj_cls_DataSet_GEN.f_TBL_DEPARTMENTS("L_ALL", pId);
                    DataSet ds = obj_cls_DataSet_GEN.g_TBL_DEPARTMENTS;
                    if (ds == null)
                    {
                        obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                        Referesh("False");
                        return;

                    }

                    dt_Datanavigator = ds.Tables[0].Copy();
                    obj_frm_TBL_DEPARTMENTS.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                }
                else
                {

                    string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][0].ToString();
                    selection("V", ID);
                }
            }
            else if (pStatus == "A")
            {

                obj_cls_DataSet_GEN.f_TBL_DEPARTMENTS("A", pId);
                DataSet ds = obj_cls_DataSet_GEN.g_TBL_DEPARTMENTS;

                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }


                obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150", 1);
                obj_frlLOOKUP.ShowDialog();
                string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                if (value != "")
                {
                    string[] cols_values = value.Split('|');
                    obj_frm_TBL_DEPARTMENTS.CheckEdit_navigate.Checked = false;
                    selection("V", cols_values[0]);
                }

            }
            else
            {

                obj_frm_TBL_DEPARTMENTS.maxID = obj_frm_TBL_DEPARTMENTS.TextEdit_DEPARTMENT_ID.Text = pId;
                obj_cls_DataSet_GEN.f_TBL_DEPARTMENTS("V", pId);
                DataSet ds = obj_cls_DataSet_GEN.g_TBL_DEPARTMENTS;
                string executeFunctions = "";

                if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                {
                    executeFunctions = valueSetting(ds);
                }
                else
                {

                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                    Referesh("False");
                    return;

                }


                if (executeFunctions != "ok")
                {
                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                    return;

                    Referesh("False");


                }


            }

        }



        //VVVGRIDINFOVVV



    }
}
