using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;

namespace PRESENTATION_LAYER.IMS_PRESENTATION_LAYER.Forms.TBL_PACKINGS_MAIN
{
    public class cls_TBL_PACKINGS_MAIN_P
    {

        Boolean isAllowedInsertion = true, isAllowedUpdation = true, isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;

        GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;

        GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

        DATASET.IMS_DATASET.cls_DataSet obj_cls_DataSet_IMS = new DATASET.IMS_DATASET.cls_DataSet();

        GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

        BLL.IMS_BLL.TBL_PACKINGS_MAIN.cls_TBL_PACKINGS_MAIN obj_cls_TBL_PACKINGS_MAIN = new BLL.IMS_BLL.TBL_PACKINGS_MAIN.cls_TBL_PACKINGS_MAIN();

        frm_TBL_PACKINGS_MAIN obj_frm_TBL_PACKINGS_MAIN = null;

        DataTable dt_Datanavigator = new DataTable();
        DataTable dt_tempForChildUnits = new DataTable();

                

        void InitializeComponents(frm_TBL_PACKINGS_MAIN pobj_frm_TBL_PACKINGS_MAIN, String pID)
        {

            obj_frm_TBL_PACKINGS_MAIN = pobj_frm_TBL_PACKINGS_MAIN;
            GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_PACKINGS_MAIN, 'A');
            obj_cls_TBL_PACKINGS_MAIN.obj_XtraForm = pobj_frm_TBL_PACKINGS_MAIN;

            if (!obj_cls_TBL_PACKINGS_MAIN.Open())
                obj_frm_TBL_PACKINGS_MAIN.Close();



            if (pID == "N")
                Referesh("True");
            else
            {
                obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.Text = pID;

                selection("V", obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.Text.Trim());

            }

        }


        public cls_TBL_PACKINGS_MAIN_P(frm_TBL_PACKINGS_MAIN pobj_frm_TBL_PACKINGS_MAIN, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, bool pIs_DisturbanceOnce)//VVVParamVVV
        {
            ObjGenForm = pObjGenForm;
            isDisturebedOnce = pIs_DisturbanceOnce;
            InitializeComponents(pobj_frm_TBL_PACKINGS_MAIN, pID);
            addUnitsToInsertInDetails();

        }


        public bool validate(out string value, bool pIs_Delete)
        {
            if (pIs_Delete)
            {

                if (!isAllowedDeletion)
                {
                    value = obj_cls_MessageBox.error_delete_rights;
                    return false;

                }

                if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'I')
                {
                    value = obj_cls_MessageBox.error_selection_msg;
                    return false;
                }

            }
            else
            {
                if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'I')
                {
                    if (!isAllowedInsertion)
                    {
                        value = obj_cls_MessageBox.error_insert_rights;
                        return false;

                    }

                }
                if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'U')
                {
                    if (!isAllowedUpdation)
                    {
                        value = obj_cls_MessageBox.error_update_rights;
                        return false;

                    }

                }

                if (Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_name.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_Name_msg;
                    obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_name.Focus();
                    obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_name.Properties.AppearanceFocused.BorderColor = System.Drawing.Color.Red;
                    return false;
                }
            }

            if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'U')
                if (Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }
            if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'I')
                if (!obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }


            value = "N";
            return true;
        }




        public void getMax()
        {
            if (obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
            {

                int tempID = obj_cls_DataSet_IMS.f_GETMAX("TBL_PACKINGS_MAIN", 0, 0, 0, "", "", "");
                obj_frm_TBL_PACKINGS_MAIN.maxID = tempID.ToString();
                obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.Text = obj_frm_TBL_PACKINGS_MAIN.maxID;

            }
        }



        public void loadGridLookUpEdit(string Status)
        {

                    if (Status == "TBL_UNITS")
                        IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_UNITS(obj_frm_TBL_PACKINGS_MAIN.GridLookUpEdit_PACKING_MAIN_parentUnit,"L","");

        }

        public string valueGetting(bool pIs_Delete)
        {

            try
            {

                string validate_value = "";

                if (!validate(out validate_value, pIs_Delete))
                {

                    if (validate_value == "N")
                        return "V_P";
                    else
                        return validate_value;

                }

                if (pIs_Delete)
                {
                    obj_cls_TBL_PACKINGS_MAIN.STATUS = "D";
                    obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_ID = Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue);
                }
                {

                    obj_cls_TBL_PACKINGS_MAIN.Is_Auto_Generated = obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Checked;

                    if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'I')
                    {

                        if (!obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                            obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_ID = Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue);
                    }
                    else
                        obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_ID = Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue);


                    obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_ID = Convert.ToString(obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.EditValue);
                    obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_name = obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_name.EditValue.ToString().Trim();
                    obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_maxLevel = obj_frm_TBL_PACKINGS_MAIN.ComboBoxEdit_PACKING_MAIN_maxLevel.EditValue.ToString().Trim();
                    obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_parentUnit = obj_frm_TBL_PACKINGS_MAIN.GridLookUpEdit_PACKING_MAIN_parentUnit.EditValue.ToString().Trim();


                }



            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }
        public string valueSetting(DataSet ds)
        {

            try
            {

                DataTable dt_Main = ds.Tables[0];

                obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_name.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_PACKINGS_MAIN.cls_CTBL_PACKINGS_MAIN.PACKING_MAIN_name];
                obj_frm_TBL_PACKINGS_MAIN.ComboBoxEdit_PACKING_MAIN_maxLevel.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_PACKINGS_MAIN.cls_CTBL_PACKINGS_MAIN.PACKING_MAIN_maxLevel];
                obj_frm_TBL_PACKINGS_MAIN.GridLookUpEdit_PACKING_MAIN_parentUnit.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_PACKINGS_MAIN.cls_CTBL_PACKINGS_MAIN.PACKING_MAIN_parentUnit];

                obj_frm_TBL_PACKINGS_MAIN.DBStatus = 'U';
                obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = false;
            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }


        public void Referesh(String isComplete)
        {

            if (isComplete == "True")
            {

                //try
                //{
                //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                //    foreach (DataRow d in drr)
                //    {
                //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                //        {
                //            isAllowedDeletion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                //        {
                //            isAllowedInsertion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                //        {
                //            isAllowedUpdation = true;
                //        }
                //    }

                //}
                //catch (Exception ex)
                //{
                //    //throw;
                //}



                        loadGridLookUpEdit("TBL_UNITS");

                obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                if (!isAllowedInsertion && !isAllowedUpdation)
                    obj_frm_TBL_PACKINGS_MAIN.SimpleButton_Save.Enabled = false;
                if (!isAllowedDeletion)
                    obj_frm_TBL_PACKINGS_MAIN.SimpleButton_Delete.Enabled = false;

                selection("N", "");
                Referesh("False");

            }
            else if (isComplete == "Partial")
            {
                
                selection("N", "");
                Referesh("False");

            }

            obj_frm_TBL_PACKINGS_MAIN.DtpackingDef.Rows.Clear();
            ObjGenForm.GenRefresh();
            obj_frm_TBL_PACKINGS_MAIN.DBStatus = 'I';
            obj_frm_TBL_PACKINGS_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = true;
            //obj_frm_TBL_PACKINGS_MAIN.CheckEdit_navigate.Checked = false;
            getMax();

        }

        public void Delete()
        {

            string executeFunctions = valueGetting(true);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }


            if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
            {

                return;

            }





            obj_cls_TBL_PACKINGS_MAIN.PACKING_MAIN_ID = obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.Text;

            if (obj_cls_TBL_PACKINGS_MAIN.deletion())
            {
                Referesh("Partial");
                if (isDisturebedOnce)
                    obj_frm_TBL_PACKINGS_MAIN.Close();
            }

        }

        public void Save()
        {
              if (obj_frm_TBL_PACKINGS_MAIN.DtpackingDef.Rows.Count < 1)
              {
                    XtraMessageBox.Show("Provide Child Units");

                    return;
              }

            string executeFunctions = valueGetting(false);
            obj_cls_TBL_PACKINGS_MAIN.dt_Def = obj_frm_TBL_PACKINGS_MAIN.DtpackingDef;
            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }

            if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'I')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_PACKINGS_MAIN.insertionUpdation('I'))
                {
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_PACKINGS_MAIN.Close();
                }


            }

            else if (obj_frm_TBL_PACKINGS_MAIN.DBStatus == 'U')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_PACKINGS_MAIN.insertionUpdation('U'))
                {
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_PACKINGS_MAIN.Close();
                }
            }

        }

        public void selection(string pStatus, string pId)
        {

            if (pStatus == "N")
            {
                if (pId == "")
                {
                    obj_cls_DataSet_IMS.f_TBL_PACKINGS_MAIN("L", pId);
                    DataSet ds = obj_cls_DataSet_IMS.g_TBL_PACKINGS_MAIN;
                    if (ds == null)
                    {
                        obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                        Referesh("False");
                        return;

                    }

                    dt_Datanavigator = ds.Tables[0].Copy();
                    obj_frm_TBL_PACKINGS_MAIN.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                }
                else
                {

                    string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][0].ToString();
                    selection("V", ID);
                }
            }
            else if (pStatus == "A")
            {

                obj_cls_DataSet_IMS.f_TBL_PACKINGS_MAIN("A", pId);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_PACKINGS_MAIN;

                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }


                obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150", 1);
                obj_frlLOOKUP.ShowDialog();
                string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                if (value != "")
                {
                    string[] cols_values = value.Split('|');
                    obj_frm_TBL_PACKINGS_MAIN.CheckEdit_navigate.Checked = false;
                    selection("V", cols_values[0]);

                }

            }
            else
            {

                obj_frm_TBL_PACKINGS_MAIN.maxID = obj_frm_TBL_PACKINGS_MAIN.TextEdit_PACKING_MAIN_ID.Text = pId;
                obj_cls_DataSet_IMS.f_TBL_PACKINGS_MAIN("V", pId);
                obj_cls_DataSet_IMS.f_TBL_PACKINGS_DEF("V", pId);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_PACKINGS_MAIN;
                DataSet ds_def = obj_cls_DataSet_IMS.g_TBL_PACKINGS_DEF;
                string executeFunctions = "";

                if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                {
                    obj_frm_TBL_PACKINGS_MAIN.DtpackingDef.Rows.Clear();
                    if (ds_def != null)
                    {
                        DataTable dd = ds_def.Tables[0];
                        foreach(DataRow dr in dd.Rows)
                        {
                            obj_frm_TBL_PACKINGS_MAIN.DtpackingDef.Rows.Add(dr[0],dr[1],dr[2],dr[3],dr[4]);
                        }
                    }
                    
                   
                    executeFunctions = valueSetting(ds);
                }
                else
                {

                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                    Referesh("False");
                    return;

                }


                if (executeFunctions != "ok")
                {
                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                    return;

                    Referesh("False");


                }


            }

        }


        void initializeDataTableToAddUnitsToInsertInDetails()
        { 
        
                    //dt_tempForChildUnits.Columns.Add("FK",typeof(System.String));
                    //dt_tempForChildUnits.Columns.Add("PK", typeof(System.String));
                    //dt_tempForChildUnits.Columns.Add("Unit", typeof(System.String));
                    //dt_tempForChildUnits.Columns.Add("QTY", typeof(System.Int32));
                    //dt_tempForChildUnits.Columns.Add("Leve", typeof(System.Int32));


        }
        void addUnitsToInsertInDetails()
        {
                    //dt_tempForChildUnits.Clear();
                    //dt_tempForChildUnits.Rows.Add(
                    //            "N",
                    //            "1",
                    //            obj_frm_TBL_PACKINGS_MAIN.GridLookUpEdit_PACKING_MAIN_parentUnit.EditValue.ToString(),
                    //            0,
                    //            1);
                    



        }


        //VVVGRIDINFOVVV



    }
}
