using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;
using BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN;
using BLL.IMS_BLL.TBL_UNITS;
using BLL.IMS_BLL.TBL_PRODUCTS;
using BLL.IMS_BLL.TBL_CUSTOMERS;
using BLL.IMS_BLL.TBL_STOCKS;
using BLL.ACC_BLL.TBL_VCH_MAIN;



namespace PRESENTATION_LAYER.IMS_PRESENTATION_LAYER.Forms.TBL_SALES_AND_RETURN_MAIN
{
    public class cls_TBL_SALES_AND_RETURN_MAIN_P
    {


        Boolean isAllowedInsertion = true, isAllowedUpdation = true, isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;
        public Boolean isRefereshing = false;
        string GV_COA_SALES = "", GV_COA_cashInHand = "", GV_COA_discount = "", GV_COA_supplier = "";
        string GV_Unit1 = "", GV_Unit2 = "", GV_Unit3 = "";
        int STOCK_maxID = 0;

        GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;
        GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView ObjGenGrid;



        GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

        DATASET.IMS_DATASET.cls_DataSet obj_cls_DataSet_IMS = new DATASET.IMS_DATASET.cls_DataSet();

        GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

        BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_TBL_SALES_AND_RETURN_MAIN obj_cls_TBL_SALES_AND_RETURN_MAIN = new BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_TBL_SALES_AND_RETURN_MAIN();

        frm_TBL_SALES_AND_RETURN_MAIN obj_frm_TBL_SALES_AND_RETURN_MAIN = null;

        DataTable dt_Datanavigator = new DataTable();
        DataTable DT_dataTableForGrid = new DataTable();
        DataTable DT_VCH = new DataTable();


        public string SALES_AND_RETURN_MAIN_cashOrCredit;
        public string SALES_AND_RETURN_MAIN_SALESOrReturn;

        void InitializeComponents(frm_TBL_SALES_AND_RETURN_MAIN pobj_frm_TBL_SALES_AND_RETURN_MAIN, String pID, string pSALES_AND_RETURN_MAIN_cashOrCredit, string pSALES_AND_RETURN_MAIN_SALESOrReturn)
        {
            SALES_AND_RETURN_MAIN_cashOrCredit = pSALES_AND_RETURN_MAIN_cashOrCredit;
            SALES_AND_RETURN_MAIN_SALESOrReturn = pSALES_AND_RETURN_MAIN_SALESOrReturn;
            obj_frm_TBL_SALES_AND_RETURN_MAIN = pobj_frm_TBL_SALES_AND_RETURN_MAIN;
            GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_SALES_AND_RETURN_MAIN, 'A');
            obj_cls_TBL_SALES_AND_RETURN_MAIN.obj_XtraForm = pobj_frm_TBL_SALES_AND_RETURN_MAIN;

            if (!obj_cls_TBL_SALES_AND_RETURN_MAIN.Open())
                obj_frm_TBL_SALES_AND_RETURN_MAIN.Close();

            GV_COA_discount = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Sales_Discount;
            GV_COA_cashInHand = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Cash_In_Hand;

            if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales Return")
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_InvoiceIDWhenReturnSelected.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_InvoiceIDWhenReturnSelected.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.SimpleButton_listForInvoicesWhenReturnSelected.Visible = true;
                obj_cls_TBL_SALES_AND_RETURN_MAIN.add = "Add";
                //obj_frm_TBL_SALES_AND_RETURN_MAIN.add = "Add";
            }
            else
                obj_cls_TBL_SALES_AND_RETURN_MAIN.add = "Remove";
            //obj_frm_TBL_SALES_AND_RETURN_MAIN.add = "Remove";


            //obj_cls_TBL_SALES_AND_RETURN_MAIN.add = "Remove";

            if (SALES_AND_RETURN_MAIN_cashOrCredit == "Cash")
            {
                if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales")
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.Text = "Cash Sales";
                    //GV_COA_SALES = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Cash_Sales;

                }
                else
                    if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales Return")
                    {
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.Text = "Cash Sales Return";
                        //GV_COA_SALES = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Cash_Sales_Return;
                    }
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Enabled = true;

            }
            if (SALES_AND_RETURN_MAIN_cashOrCredit == "Credit")
            {


                if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales")
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.Text = "Sales";
                    GV_COA_SALES = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Credit_Sales;
                }
                else
                    if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales Return")
                    {
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.Text = " Sales Return";
                        GV_COA_SALES = GEN.GEN_GEN.GenericClasses.cls_KeysWithValue.Credit_Sales_Returns;
                    }

            }


            if (pID == "N")
                Referesh("True");
            else
            {
                Referesh("True");
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text = pID;

                selection("V", obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text.Trim());

            }

        }


        public cls_TBL_SALES_AND_RETURN_MAIN_P(frm_TBL_SALES_AND_RETURN_MAIN pobj_frm_TBL_SALES_AND_RETURN_MAIN, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView pObjGenGrid, bool pIs_DisturbanceOnce, string pSALES_AND_RETURN_MAIN_cashOrCredit, string pSALES_AND_RETURN_MAIN_SALESOrReturn)//VVVParamVVV
        {
            ObjGenForm = pObjGenForm;
            ObjGenGrid = pObjGenGrid;
            isDisturebedOnce = pIs_DisturbanceOnce;
            InitializeComponents(pobj_frm_TBL_SALES_AND_RETURN_MAIN, pID, pSALES_AND_RETURN_MAIN_cashOrCredit, pSALES_AND_RETURN_MAIN_SALESOrReturn);

        }


        public bool validate(out string value, bool pIs_Delete)
        {
            if (pIs_Delete)
            {

                if (!isAllowedDeletion)
                {
                    value = obj_cls_MessageBox.error_delete_rights;
                    return false;

                }

                if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'I')
                {
                    value = obj_cls_MessageBox.error_selection_msg;
                    return false;
                }

            }
            else
            {
                if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'I')
                {
                    if (!isAllowedInsertion)
                    {
                        value = obj_cls_MessageBox.error_insert_rights;
                        return false;

                    }

                }
                if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'U')
                {
                    if (!isAllowedUpdation)
                    {
                        value = obj_cls_MessageBox.error_update_rights;
                        return false;

                    }

                }

                if (Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_Name_msg;
                    GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID);
                    return false;
                }

                if (Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_Phone.EditValue) != "")
                {
                   
                    if (Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays.EditValue) == "")
                    {
                        value = obj_cls_MessageBox.error_Name_msg;
                        GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays);
                        return false;
                    }

                    else
                    {

                        int days = Convert.ToInt16(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays.EditValue);
                        if (days < 1)
                        {
                            value = obj_cls_MessageBox.error_Name_msg;
                            GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays);
                            return false;
                        }

                    }



                    if (Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_nextMileage.EditValue) == "")
                    {
                        value = obj_cls_MessageBox.error_Name_msg;
                        GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_nextMileage);
                        return false;
                    }
                }


                if (DT_dataTableForGrid.Rows.Count == 0)
                {

                    value = "V_P";
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.Focus();
                    return false;

                }




            }

            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'U')
                if (Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }
            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'I')
                if (!obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }



            calculations(true);

            value = "N";
            return true;
        }




        public void getMax()
        {
            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
            {

                int tempID = obj_cls_DataSet_IMS.f_GETMAX("TBL_SALES_AND_RETURN_MAIN", 0, 0, 0, "", "", "");
                obj_frm_TBL_SALES_AND_RETURN_MAIN.maxID = tempID.ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text = obj_frm_TBL_SALES_AND_RETURN_MAIN.maxID;

            }
        }



        public void loadGridLookUpEdit(string Status)
        {


            //IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_SUPPLIERS(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID);
            if (Status == "TBL_CUSTOMERS")

                IMS_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_CUSTOMERS(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID);

            if (Status == "TBL_PRODUCTS_costRateHistory")

                IMS_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_PRODUCTScostRateHistory(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCostRateHistory, obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode.EditValue.ToString());

            else if (Status == "TBL_PRODUCTS")
            {

                IMS_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_PRODUCTS(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsName, BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_name);
                IMS_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_PRODUCTS(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode, BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_COA);

            }

            else if (Status == "TBL_UNITS")
            {
                IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_UNITS(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits, "Units Against An Item", obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsName.EditValue.ToString());
                //obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.Properties.GetKeyValue(0);
                // setRatesAgainstUnit(true);
            }




        }

        public string valueGetting(bool pIs_Delete)
        {

            try
            {

                string validate_value = "";

                if (!validate(out validate_value, pIs_Delete))
                {

                    if (validate_value == "N")
                        return "V_P";
                    else
                        return validate_value;

                }

                if (pIs_Delete)
                {
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.STATUS = "D";
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_ID = Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue);
                }

                {
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.dt_Detail = DT_dataTableForGrid;
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.dt_DetailVCH = DT_VCH;

                    obj_cls_TBL_SALES_AND_RETURN_MAIN.Is_Auto_Generated = obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Checked;

                    if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'I')
                    {

                        if (!obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                            obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_ID = Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue);
                    }
                    else
                        obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_ID = Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue);

                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_supplierID = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_cashOrCredit = SALES_AND_RETURN_MAIN_cashOrCredit;//TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_cashOrCredit.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_SALESOrReturn = SALES_AND_RETURN_MAIN_SALESOrReturn;// obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_SALESOrReturn.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_date = obj_frm_TBL_SALES_AND_RETURN_MAIN.DateEdit_SALES_AND_RETURN_MAIN_date.DateTime.Date;
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_reference = "";// obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_reference.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_narration = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim();

                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_totalAmount = Convert.ToDecimal(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalAmount.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalAmount.EditValue.ToString().Trim());
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_totalPayableAmount = Convert.ToDecimal(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.EditValue.ToString().Trim());
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_discountAmount = Convert.ToDecimal(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.EditValue.ToString().Trim());
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_paidAmount = Convert.ToDecimal(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.EditValue.ToString().Trim());
                    //obj_cls_TBL_SALES_AND_RETURN_MAIN.add = "Remove";
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.STOCK_maxID = STOCK_maxID; //obj_frm_TBL_SALES_AND_RETURN_MAIN.ComboBox_addRemove.SelectedItem.ToString();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Maker = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Maker.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Model = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Model.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Mileage = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Mileage.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_VehicleNumber = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_VehicleNumber.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.Message_Limit = obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.Phone = obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_Phone.EditValue.ToString().Trim();
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.Next_Milleage = obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_nextMileage.EditValue.ToString().Trim();


                }



            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }
        public string valueSetting(DataSet ds, char pDBStatus)
        {

            try
            {

                DataTable dt_Main = ds.Tables[0];
                DT_dataTableForGrid = ds.Tables[1].Copy();
                initiateGrid(false);

                if (pDBStatus == 'U')
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];
                    obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_VCHID = (string)dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_VCHID];
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = false;

                }


                //  obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_ID = Convert.ToString(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue);

                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.EditValue = obj_frm_TBL_SALES_AND_RETURN_MAIN.maxID = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.priSALES_AND_RETURN_MAIN_ID].ToString();

                obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_supplierID];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.DateEdit_SALES_AND_RETURN_MAIN_date.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_date];
                //obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_reference.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_reference];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_narration];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalAmount.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_totalAmount];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_totalPayableAmount];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_discountAmount];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_paidAmount];
                STOCK_maxID = (int)dt_Main.Rows[0][BLL.IMS_BLL.TBL_STOCKS.cls_CTBL_STOCKS.STOCK_maxID];

                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Maker.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Maker];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Model.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Model];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_Mileage.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_Mileage];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_VehicleNumber.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_VehicleNumber];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_messageDays.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.Message_Limit];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_nextMileage.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.Next_Milleage];
                obj_frm_TBL_SALES_AND_RETURN_MAIN.textEdit_Phone.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_SALES_AND_RETURN_MAIN.cls_CTBL_SALES_AND_RETURN_MAIN.phone];

                obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus = pDBStatus;
                //obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.SelectedIndex = 2;




            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }





        public void Referesh(String isComplete)
        {

            if (isComplete == "True")
            {
                isRefereshing = true;

                //try
                //{
                //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                //    foreach (DataRow d in drr)
                //    {
                //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                //        {
                //            isAllowedDeletion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                //        {
                //            isAllowedInsertion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                //        {
                //            isAllowedUpdation = true;
                //        }
                //    }

                //}
                //catch (Exception ex)
                //{
                //    //throw;
                //}



                loadGridLookUpEdit("TBL_CUSTOMERS");
                loadGridLookUpEdit("TBL_PRODUCTS");

                obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                if (!isAllowedInsertion && !isAllowedUpdation)
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.SimpleButton_Save.Enabled = false;
                if (!isAllowedDeletion)
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.SimpleButton_Delete.Enabled = false;
                initiateGrid(true);
                selection("N", "");
                Referesh("False");


            }
            else if (isComplete == "Partial")
            {
                isRefereshing = true;
                selection("N", "");
                Referesh("False");
                obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.SelectedIndex = 0;


            }
            isRefereshing = true;

            ObjGenForm.GenRefresh();
            obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus = 'I';
            obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = true;
            //obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_navigate.Checked = false;
            getMax();
            DT_dataTableForGrid.Rows.Clear();
            isRefereshing = false;
            selectItemDetailsINfo("Single Product Info For Transaction Against Product ID");


        }

        public void Delete()
        {

            string executeFunctions = valueGetting(true);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }


            if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
            {

                return;

            }





            obj_cls_TBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_MAIN_ID = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text;

            if (obj_cls_TBL_SALES_AND_RETURN_MAIN.deletion())
            {
                Referesh("Partial");
                if (isDisturebedOnce)
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.Close();
            }

        }

        public void Save(bool isPrint)
        {
            string pID = "";

            string executeFunctions = valueGetting(false);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }

            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'I')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_SALES_AND_RETURN_MAIN.insertionUpdation('I', out pID))
                {
                    if (isPrint)
                        showReport(pID);
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.Close();
                }


            }

            else if (obj_frm_TBL_SALES_AND_RETURN_MAIN.DBStatus == 'U')
            {

                if (PRESENTATION_LAYER.GEN_PRESENTATION_LAYER.cls_StaticObjects.user_name != "admin")
                {

                    XtraMessageBox.Show("You have no rights to update the invocie");
                    XtraMessageBox.Show(PRESENTATION_LAYER.GEN_PRESENTATION_LAYER.cls_StaticObjects.user_name);

                    return;
 

                }

                if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_SALES_AND_RETURN_MAIN.insertionUpdation('U', out pID))
                {
                    //if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_smallOrLarge.EditValue == "Preview")
                    //    showReport(pID);
                  
                    //showReport(pID);

                    if (isPrint)
                        showReport(pID);



                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.Close();
                }
            }






        }

        void showReport(string pID)
        {

            if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales")
            {

                if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_smallOrLarge.EditValue == "Small")
                {

                    IMS_PRESENTATION_LAYER.Reports.Sales.SaleInvoice.DM.rpt_DETAIL_SALE_INVOICE_SMALL obj_rpt_DETAIL_SALE_INVOICE_SMALL = new Reports.Sales.SaleInvoice.DM.rpt_DETAIL_SALE_INVOICE_SMALL(pID);
                    DevExpress.XtraReports.UI.ReportPrintTool objt = new DevExpress.XtraReports.UI.ReportPrintTool(obj_rpt_DETAIL_SALE_INVOICE_SMALL);

                    if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Print")
                        objt.Print();
                    else if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Preview")
                        objt.ShowPreview();

                }
                else
                {
                    IMS_PRESENTATION_LAYER.Reports.Sales.SaleInvoice.DM.rpt_DETAIL_SALE_INVOICE obj_rpt_DETAIL_SALE_INVOICE = new Reports.Sales.SaleInvoice.DM.rpt_DETAIL_SALE_INVOICE(pID);
                    DevExpress.XtraReports.UI.ReportPrintTool objt = new DevExpress.XtraReports.UI.ReportPrintTool(obj_rpt_DETAIL_SALE_INVOICE);

                    if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Print")
                        objt.Print();
                    else if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Preview")
                        objt.ShowPreview();
                }
            }
        }



        public void selection(string pStatus, string pId)
        {


            if (pStatus == "N")
            {
                if (pId == "")
                {
                    obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("L", pId, SALES_AND_RETURN_MAIN_cashOrCredit, SALES_AND_RETURN_MAIN_SALESOrReturn);
                    DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;
                    if (ds == null)
                    {
                        obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                        Referesh("False");
                        return;

                    }

                    dt_Datanavigator = ds.Tables[0].Copy();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                }
                else
                {

                    string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][cls_CTBL_SALES_AND_RETURN_MAIN.priSALES_AND_RETURN_MAIN_ID].ToString();
                    selection("V", ID);
                }
            }
            else if (pStatus == "A")
            {

                obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("A", pId, SALES_AND_RETURN_MAIN_cashOrCredit, SALES_AND_RETURN_MAIN_SALESOrReturn);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;

                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }


                obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150,150,150,150,150", 1);
                obj_frlLOOKUP.ShowDialog();
                string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                if (value != "")
                {
                    string[] cols_values = value.Split('|');
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_navigate.Checked = false;
                    selection("V", cols_values[0]);
                }

            }
            else if (pStatus == "G")
            {
                obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("G", pId, SALES_AND_RETURN_MAIN_cashOrCredit, SALES_AND_RETURN_MAIN_SALESOrReturn);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;
                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }

                DT_dataTableForGrid = ds.Tables[0].Copy();
            }
            else
            {

                obj_frm_TBL_SALES_AND_RETURN_MAIN.maxID = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text = pId;
                obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("V", pId, SALES_AND_RETURN_MAIN_cashOrCredit, SALES_AND_RETURN_MAIN_SALESOrReturn);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;
                string executeFunctions = "";

                if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                {
                    executeFunctions = valueSetting(ds, 'U');
                }
                else
                {

                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                    Referesh("False");
                    return;

                }


                if (executeFunctions != "ok")
                {
                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                    return;

                    Referesh("False");


                }


            }

        }

        public void selectionInvoiceWhenReturnIsSelected(string pStatus, string pId)
        {


            if (pStatus == "A")
            {

                obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("A", pId, SALES_AND_RETURN_MAIN_cashOrCredit, "Sales");
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;

                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }


                obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150,150,150,150,150", 1);
                obj_frlLOOKUP.ShowDialog();
                string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                if (value != "")
                {
                    string[] cols_values = value.Split('|');
                    //obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_navigate.Checked = false;
                    selectionInvoiceWhenReturnIsSelected("V", cols_values[0]);
                }

            }
            else
            {


                //obj_frm_TBL_SALES_AND_RETURN_MAIN.maxID = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_ID.Text = pId;
                obj_cls_DataSet_IMS.f_TBL_SALES_AND_RETURN_MAIN("V", pId, SALES_AND_RETURN_MAIN_cashOrCredit, "Sales");
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_SALES_AND_RETURN_MAIN;
                string executeFunctions = "";

                if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                {
                    executeFunctions = valueSetting(ds, 'I');
                }
                else
                {

                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                    Referesh("False");
                    return;

                }


                if (executeFunctions != "ok")
                {
                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                    return;

                    Referesh("False");


                }


            }

        }


        public void loadlastProductInforFromCostRateHistory()
        {

            string lastUnit = "";
            double QTY = 0;
            double Cost = 0;



            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCostRateHistory.EditValue != null)
            {

                DataRow _Dr = (obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCostRateHistory.Properties.GetRowByKeyValue(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCostRateHistory.EditValue.ToString()) as DataRowView).Row;
                lastUnit = _Dr[cls_CTBL_STOCKS.STOCK_unit].ToString();
                QTY = (double)_Dr["QTYs"];
                Cost = (double)_Dr["Costs"];




            }
            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text = Cost.ToString();
            if (!obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_lastQTY.Checked)
            {
                if (lastUnit != "")
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = lastUnit;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.Text = QTY.ToString();
            }

        }



        public void selectItemDetailsINfo(string pStatus)
        {
            //if (isRefereshing)
            //      return;




            string pId = "";
            if (pStatus == "Single Product Info For Transaction Against Product ID")

                pId = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode.EditValue.ToString();

            else
                pId = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.EditValue.ToString();





            obj_cls_DataSet_IMS.f_TBL_PRODUCTS(pStatus, pId);
            DataSet ds = obj_cls_DataSet_IMS.g_TBL_PRODUCTS;
            if (GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
            {
                if (pStatus == "Single Product Info For Transaction Against Product ID")
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                else
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.EditValue = "";
                return;

            }


            GV_Unit1 = ds.Tables[0].Rows[0]["U1_ID"].ToString();
            GV_Unit2 = ds.Tables[0].Rows[0]["U2_ID"].ToString();
            GV_Unit3 = ds.Tables[0].Rows[0]["U3_ID"].ToString();
            string GV_default = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_defaultLevel].ToString();





            if (pStatus == "Single Product Info For Transaction Against Product Barcode")
                obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode.EditValue = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsName.EditValue = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.priPRODUCT_ID].ToString();

            if (pStatus == "Single Product Info For Transaction Against Product ID")
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.EditValue = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_barCode].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.EditValue = "";
            }
            //else
            //      obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsBarcode.EditValue = "";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.EditValue = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_saleRate].ToString();
            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.EditValue = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_purchaseRate].ToString();

            loadGridLookUpEdit("TBL_UNITS");
            loadGridLookUpEdit("TBL_PRODUCTS_costRateHistory");




            if (GV_default == "1")
                obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = GV_Unit1;
            else
                if (GV_default == "2")
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = GV_Unit2;
                else
                    if (GV_default == "3")
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = GV_Unit3;



            setRatesAgainstUnit(true);

            //if (ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_lastSaleUnit].ToString() != "")
            //      obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = //ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_lastSaleUnit].ToString();
            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.Text = "1";

            if (obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_lastQTY.Checked)
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.Text = ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_lastSaleQTY].ToString() == "" ? "1" : ds.Tables[0].Rows[0][BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_lastSaleQTY].ToString();
            else
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.Text = "1";

            if (pStatus == "Single Product Info For Transaction Against Product Barcode")
                if (obj_frm_TBL_SALES_AND_RETURN_MAIN.CheckEdit_isAddedAutomatically.Checked)
                    addRow();


            //loadlastProductInforFromCostRateHistory();


            string maxLevel = ds.Tables[0].Rows[0]["PACKING_MAIN_maxLevel"].ToString();

            if (maxLevel == "1")
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = ds.Tables[0].Rows[0]["closingQTY1"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = ds.Tables[0].Rows[0]["U1_name"].ToString();

                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = false;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = false;

            }
            else if (maxLevel == "2")
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = ds.Tables[0].Rows[0]["closingQTY1"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = ds.Tables[0].Rows[0]["U1_name"].ToString();


                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.EditValue = ds.Tables[0].Rows[0]["closingQTY2"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Text = ds.Tables[0].Rows[0]["U2_name"].ToString();



                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = true;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = false;

            }
            else if (maxLevel == "3")
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = ds.Tables[0].Rows[0]["closingQTY1"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = ds.Tables[0].Rows[0]["U1_name"].ToString();


                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.EditValue = ds.Tables[0].Rows[0]["closingQTY2"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Text = ds.Tables[0].Rows[0]["U2_name"].ToString();

                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.EditValue = ds.Tables[0].Rows[0]["closingQTY3"].ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Text = ds.Tables[0].Rows[0]["U3_name"].ToString();



                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = true;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = true;

            }


            //getlastQTYBalance();

            //setRatesAgainstUnit();

        }

        public void initiateGrid(bool isNew)
        {
            if (isNew)
                selection("G", "");
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridControl_SALES_AND_RETURN_DETAILS.DataSource = DT_dataTableForGrid;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.PopulateColumns();

            //GEN.GEN_GEN.GenericClasses.Grid.cls_GridAppearance.setAppearance(obj_frm_TBL_TEMP_MAIN.GridView_TBL_TEMP_DET, "I");

            // A_SALES_AND_RETURN_DETAILS_itemCOA

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCOA].Caption = "Code";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCOA].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCOA].Width = 65;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCOA].Tag = "N|N|Y|Y";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCOA].OptionsColumn.AllowEdit = false;



            // A_SALES_AND_RETURN_DETAILS_itemName

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemName].Caption = "Product";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemName].OptionsColumn.FixedWidth = false;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemName].Width = 100;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemName].Tag = "N|C|Y|Y";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemName].OptionsColumn.AllowEdit = false;

            // A_SALES_AND_RETURN_DETAILS_itemCode

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemCode].Visible = false;


            // SALES_AND_RETURN_DETAILS_itemUnit

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_itemUnit].Caption = "Unit";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_itemUnit].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_itemUnit].Width = 75;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_itemUnit].Tag = "N|N|N|N";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_itemUnit].OptionsColumn.AllowEdit = false;

            // A_SALES_AND_RETURN_DETAILS_itemUnitCode

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.A_SALES_AND_RETURN_DETAILS_itemUnitCode].Visible = false;



            // SALES_AND_RETURN_DETAILS_SALESPrice

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_SALESPrice].Caption = "Rate";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_SALESPrice].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_SALESPrice].Width = 100;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_SALESPrice].Tag = "N2|A|Y|N";

            // SALES_AND_RETURN_DETAILS_CostPrice

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_costPrice].Caption = "Cost";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_costPrice].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_costPrice].Width = 100;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_costPrice].Tag = "N2|A|Y|N";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_costPrice].Visible = false;


            // SALES_AND_RETURN_DETAILS_QTY

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_QTY].Caption = "Qty";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_QTY].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_QTY].Width = 100;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_QTY].Tag = "N2|S|Y|N";


            // SALES_AND_RETURN_DETAILS_total

            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].Caption = "Total";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].OptionsColumn.FixedWidth = true;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].Width = 100;
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].Tag = "N2|S|Y|N";
            obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].OptionsColumn.AllowEdit = false;





            //SALES_AND_RETURN_DETAILS_itemID



            ObjGenGrid.Formatting();
        }


        public void addRow()
        {
            double tmpRate = Convert.ToDouble((obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.EditValue.ToString() == "0" || obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.EditValue.ToString() == "") ? "1" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text);
            double tmpCostRate = Convert.ToDouble((obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.EditValue.ToString() == "0" || obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.EditValue.ToString() == "") ? "1" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text);

            double tmpQTY = Convert.ToDouble((obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.EditValue.ToString() == "0" || obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.EditValue.ToString() == "") ? "1" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productQty.Text);
            double tmptotal = (tmpQTY * tmpRate);

            //bool isQTYfine = false;

            //double tmpclosingQT1 = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue.ToString());
            //double tmpclosingQT2 = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.EditValue);
            //double tmpclosingQT3 =Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.EditValue);

            //if (tmpclosingQT1 > 0 || tmpclosingQT2 > 0 || tmpclosingQT3 > 0)
            //{

            //      string unitID = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue.ToString();
            //      if(unitID == GV_Unit1 && tmpQTY >tmpclosingQT1)
            //            isQTYfine = false;
            //      if (unitID == GV_Unit2 && tmpQTY > tmpclosingQT2)
            //            isQTYfine = false;
            //      if (unitID == GV_Unit3 && tmpQTY > tmpclosingQT3)
            //            isQTYfine = false;


            //}
            //else
            //      isQTYfine = false;

            //if (!isQTYfine)
            //{

            //      obj_cls_MessageBox.MessageBoxStatic("Not Enough Stock To Sale");
            //      return;

            //}



            DT_dataTableForGrid.Rows.Add(

                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode.Text,
                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsName.Text,
                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsName.EditValue,

                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.Text,
                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue,

                  tmpCostRate,
                  tmpRate,//obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text == "" ? 0 : Convert.ToDouble( obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text),
                  tmpQTY,
                  tmptotal//obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text == "" ? 0 : Convert.ToDouble( obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text)


                  );

            calculations(false);

        }

        public bool iscashSale = true;

        public void calculations(bool pIsFinalCalculation)
        {


            
           

            double tmptotal = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].SummaryItem.SummaryValue.ToString() == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.GridView_SALES_AND_RETURN_DETAILS.Columns[cls_CTBL_SALES_AND_RETURN_MAIN.SALES_AND_RETURN_DETAILS_total].SummaryItem.SummaryValue.ToString());
            double tmpdiscount = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.Text);
            double tmptotalPaid = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text);
            double tmptotalPayAble = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.Text);
           
          

            if (tmpdiscount > tmptotal)
            {
                tmpdiscount = 0;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_discountAmount.Text = "0";
            }
            if (tmptotalPaid > tmptotal)
            {
                tmpdiscount = 0;
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text = "0";
            }


            tmptotalPaid = (tmptotal - tmptotalPayAble - tmpdiscount);


            //if (tmptotalPaid == 0)
            //{
            //    tmptotalPaid = tmptotalPayAble;
            //    tmptotalPayAble = 0;

            //}



            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.EditValue = tmptotalPaid.ToString();
            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalAmount.Text = tmptotal.ToString();

            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_totalPayableAmount.EditValue = tmptotalPayAble.ToString();

         
            //obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text = (tmptotal - tmpdiscount).ToString();
            //tmptotalPaid = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text);


            //if (SALES_AND_RETURN_MAIN_cashOrCredit == "Cash")
            //{
            //    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text = (tmptotal - tmpdiscount).ToString();
            //    tmptotalPaid = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text);

            //}
            //else if (SALES_AND_RETURN_MAIN_cashOrCredit == "Credit")
            //{
            //    tmptotalPaid = Convert.ToDouble(obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text == "" ? "0" : obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text);
            //    if (tmptotalPaid > (tmptotal - tmpdiscount))
            //        obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text = "0";
            //}

            
            //iscashSale = true;
            //obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_paidAmount.Text = (tmptotal - tmpdiscount - tmptotalPaid).ToString(); ;
            //iscashSale = false;

            if (pIsFinalCalculation)
            {

                DataRow _Dr = (obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID.Properties.GetRowByKeyValue(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_SALES_AND_RETURN_MAIN_supplierID.EditValue) as DataRowView).Row;
                GV_COA_supplier = _Dr[BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_COA].ToString();


                //Initialize the table

                DT_VCH = GEN.GEN_GEN.GenericClasses.DataTables.cls_StaticTables.getTableofVCH();



                if (SALES_AND_RETURN_MAIN_SALESOrReturn == "Sales")
                {

                    DT_VCH.Rows.Add(GV_COA_SALES, "", 0, tmptotal, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmpdiscount > 0)
                        DT_VCH.Rows.Add(GV_COA_discount, "", tmpdiscount, 0, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmptotalPaid > 0)
                        DT_VCH.Rows.Add(GV_COA_cashInHand, "", tmptotalPaid, 0, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmptotalPayAble > 0)
                        DT_VCH.Rows.Add(GV_COA_supplier, "", tmptotalPayAble, 0, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());




                }

                else
                {

                    DT_VCH.Rows.Add(GV_COA_SALES, "", tmptotal, 0, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmpdiscount > 0)
                        DT_VCH.Rows.Add(GV_COA_discount, "", 0, tmpdiscount, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmptotalPaid > 0)
                        DT_VCH.Rows.Add(GV_COA_cashInHand, "", 0, tmptotalPaid, obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());

                    if (tmptotalPaid < tmptotalPayAble)
                        DT_VCH.Rows.Add(GV_COA_supplier, "", 0, (tmptotalPayAble - tmptotalPaid), obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim());




                }




                //foreach (DataRow dr in DT_VCH.Rows)
                //{

                //    dr[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].va = obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_SALES_AND_RETURN_MAIN_narration.Text.Trim();

                //}


            }




        }


        bool getlastQTYBalance()
        {

            TBl_STOCKS.localDataSet.ds_sp_TBL_STOCK_netStockInhand_lastQTYBalnaceForSingleProductTableAdapters.sp_TBL_STOCK_netStockInhandTableAdapter obj_dataSet = new TBl_STOCKS.localDataSet.ds_sp_TBL_STOCK_netStockInhand_lastQTYBalnaceForSingleProductTableAdapters.sp_TBL_STOCK_netStockInhandTableAdapter();
            TBl_STOCKS.localDataSet.ds_sp_TBL_STOCK_netStockInhand_lastQTYBalnaceForSingleProduct.sp_TBL_STOCK_netStockInhandDataTable obj_table = new TBl_STOCKS.localDataSet.ds_sp_TBL_STOCK_netStockInhand_lastQTYBalnaceForSingleProduct.sp_TBL_STOCK_netStockInhandDataTable();
            obj_dataSet.Connection.ConnectionString = DAL.DALCustome.connectionstring;


            obj_dataSet.Fill(
                  obj_table,
                  "Per_Product_Closing_Balance",
                  "QTY",
                  GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_CMP_ID,
                  GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_BRC_ID,
                  null,
                  obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsCode.EditValue.ToString(),
                  null,
                  null,
                  GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.GV_isDeleted
                  );



            DataRow tmpDataRow = obj_table.Rows[0]; //GEN.IMS_GEN.Forms.TBL_STOCKS.TBL_STOCKS_P.ArrangeNegativeStockFromParentStock(obj_table.Rows[0]);

            if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullTableEmpty(obj_table))
            {
                string maxLevel = tmpDataRow["PACKING_MAIN_maxLevel"].ToString();

                if (maxLevel == "1")
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = tmpDataRow["netQty1"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = tmpDataRow["U1_name"].ToString();

                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = false;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = false;

                }
                else if (maxLevel == "2")
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = tmpDataRow["netQty1"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = tmpDataRow["U1_name"].ToString();


                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.EditValue = tmpDataRow["netQty2"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Text = tmpDataRow["U2_name"].ToString();



                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = true;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = false;

                }
                else if (maxLevel == "3")
                {
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.EditValue = tmpDataRow["netQty1"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Text = tmpDataRow["U1_name"].ToString();


                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.EditValue = tmpDataRow["netQty2"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Text = tmpDataRow["U2_name"].ToString();

                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.EditValue = tmpDataRow["netQty3"].ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Text = tmpDataRow["U3_name"].ToString();



                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY1.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY1.Visible = true;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY2.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY2.Visible = true;
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_balanceQTY3.Visible = obj_frm_TBL_SALES_AND_RETURN_MAIN.LabelControl_balanceQTY3.Visible = true;

                }






            }


            return true;
        }

        public void setRatesAgainstUnit(bool isFirst)
        {

            try
            {

                // obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue = "1";



                System.Data.DataRowView dr1 = (System.Data.DataRowView)obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.Properties.GetRowByKeyValue(obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.EditValue);
                DataRow dr = dr1.Row;

                // int rowhandle = 0;
                //if(!isFirst)

                //       rowhandle = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.Properties.View.FocusedRowHandle;
                ////DataRow dr = obj_frm_TBL_SALES_AND_RETURN_MAIN.GridLookUpEdit_productsUnits.Properties.View.GetDataRow(rowhandle);

                int level = Convert.ToInt16(dr[BLL.IMS_BLL.TBL_PACKINGS_DEF.cls_CTBL_PACKINGS_DEF.PACKING_DEF_level]);

                double saleRate1 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_saleRate_level1]);
                double saleRate2 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_saleRate_level2]);
                double saleRate3 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_saleRate_level3]);

                double costRate1 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_costRate_level1]);
                double costRate2 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_costRate_level2]);
                double costRate3 = Convert.ToDouble(dr[BLL.IMS_BLL.TBL_PRODUCTS.cls_CTBL_PRODUCTS.PRODUCT_costRate_level3]);

                if (level == 1)
                {

                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text = costRate1.ToString();
                    obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text = saleRate1.ToString();

                }
                else
                    if (level == 2)
                    {

                        obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text = costRate2.ToString();
                        obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text = saleRate2.ToString();

                    }
                    else
                        if (level == 3)
                        {

                            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text = costRate3.ToString();
                            obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text = saleRate3.ToString();

                        }
            }
            catch (Exception ex)
            {
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsCostRate.Text = 0.ToString();
                obj_frm_TBL_SALES_AND_RETURN_MAIN.TextEdit_productsRate.Text = 0.ToString();


            }

        }

        //VVVGRIDINFOVVV



    }
}
