using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.IO;
using System.Data.SqlClient;
using System.Data;

namespace BLL.ACC_BLL
{
//     *****************************************************************************************************************************************************************
 
 
//                             Code Type:           Business Logic Layer
//                             Creation Date:       4/27/2014 8:28:26 PM
//                             Auther:              Muhammad Usman Raza Attari
//                             Developed By :       786 Software House 
 
 
//    *****************************************************************************************************************************************************************
 
  public   class cls_TBL_ACC_PLAN
    {
      DAL.DALCustome obj_dal = new DAL.DALCustome();
 
        public Boolean  gproperty_allocatoin = false;
 
        string ExeState = "";
 
        private  char  status  ;
 
        public  char  STATUS  
        {
              get { return status; }
              set {status = value ; }
        }
 
        private  int  tBL_ACC_PLAN_MAIN_ID  = 0;
 
        public  int  TBL_ACC_PLAN_MAIN_ID  
        {
              get { return tBL_ACC_PLAN_MAIN_ID; }
              set {tBL_ACC_PLAN_MAIN_ID = value ; }
        }
 
        private  string  tBL_ACC_PLAN_MAIN_planName  = string.Empty;
 
        public  string  TBL_ACC_PLAN_MAIN_planName  
        {
              get { return tBL_ACC_PLAN_MAIN_planName; }
              set {tBL_ACC_PLAN_MAIN_planName = value ; }
        }

        private string cMP_ID = null;

       public string CMP_ID
        {
            get { return cMP_ID; }
            set { cMP_ID = value; }
        }
       private string bRC_ID = null;

       public string BRC_ID
        {
            get { return bRC_ID; }
            set { bRC_ID = value; }
        }

        private bool tBL_ACC_PLAN_MAIN_isDeleted = true;

        public bool TBL_ACC_PLAN_MAIN_isDeleted
        {
            get { return tBL_ACC_PLAN_MAIN_isDeleted; }
            set { tBL_ACC_PLAN_MAIN_isDeleted = value; }
        }

        private  int  tBL_ACC_PLAN_MAIN_maxLevel  = 0;
 
        public  int  TBL_ACC_PLAN_MAIN_maxLevel  
        {
              get { return tBL_ACC_PLAN_MAIN_maxLevel; }
              set {tBL_ACC_PLAN_MAIN_maxLevel = value ; }
        }
 
        private  string  tBL_ACC_PLAN_MAIN_format  = string.Empty;
 
        public  string  TBL_ACC_PLAN_MAIN_format  
        {
              get { return tBL_ACC_PLAN_MAIN_format; }
              set {tBL_ACC_PLAN_MAIN_format = value ; }
        }
 
        private  int  tBL_ACC_PLAN_MAIN_transactionLevel  = 0;
 
        public  int  TBL_ACC_PLAN_MAIN_transactionLevel  
        {
              get { return tBL_ACC_PLAN_MAIN_transactionLevel; }
              set {tBL_ACC_PLAN_MAIN_transactionLevel = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_MAIN_isType  = true;
 
        public  bool  TBL_ACC_PLAN_MAIN_isType  
        {
              get { return tBL_ACC_PLAN_MAIN_isType; }
              set {tBL_ACC_PLAN_MAIN_isType = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_MAIN_areAllFixed  = true;
 
        public  bool  TBL_ACC_PLAN_MAIN_areAllFixed  
        {
              get { return tBL_ACC_PLAN_MAIN_areAllFixed; }
              set {tBL_ACC_PLAN_MAIN_areAllFixed = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_MAIN_areAllAutoGenerated  = true;
 
        public  bool  TBL_ACC_PLAN_MAIN_areAllAutoGenerated  
        {
              get { return tBL_ACC_PLAN_MAIN_areAllAutoGenerated; }
              set {tBL_ACC_PLAN_MAIN_areAllAutoGenerated = value ; }
        }
 
        private  string  tBL_ACC_PLAN_MAIN_leveSeperator  = string.Empty;
 
        public  string  TBL_ACC_PLAN_MAIN_leveSeperator  
        {
              get { return tBL_ACC_PLAN_MAIN_leveSeperator; }
              set {tBL_ACC_PLAN_MAIN_leveSeperator = value ; }
        }
 
        private  string  tBL_ACC_PLAN_MAIN_description  = string.Empty;
 
        public  string  TBL_ACC_PLAN_MAIN_description  
        {
              get { return tBL_ACC_PLAN_MAIN_description; }
              set {tBL_ACC_PLAN_MAIN_description = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_MAIN_isActive  = true;
 
        public  bool  TBL_ACC_PLAN_MAIN_isActive  
        {
              get { return tBL_ACC_PLAN_MAIN_isActive; }
              set {tBL_ACC_PLAN_MAIN_isActive = value ; }
        }
 
        
        public DataSet selection()
        {

        SqlParameter[] sql_param = new SqlParameter[4];
 
        sql_param[0] = new SqlParameter("@STATUS", SqlDbType.Char);
        sql_param[0].Value = STATUS ;
        sql_param[1] = new SqlParameter("@CMP_ID", SqlDbType.NVarChar);
        sql_param[1].Value = CMP_ID;

        sql_param[2] = new SqlParameter("@BRC_ID", SqlDbType.NVarChar);
        sql_param[2].Value = BRC_ID;

        sql_param[3] = new SqlParameter("@TBL_ACC_PLAN_MAIN_isDeleted", SqlDbType.Bit);
        sql_param[3].Value = TBL_ACC_PLAN_MAIN_isDeleted;


        DataSet ds = new DataSet();

        ds = obj_dal.selection("sp_TBL_ACC_PLAN_selection", sql_param);

        if(ds == null)
        {
        return ds ;
        }

        int x = ds.Tables.Count;

         DataTable dt = new DataTable();

        dt = ds.Tables[0];

        if(gproperty_allocatoin == true)
        {
        if (dt.Rows.Count != 0)

        {

        TBL_ACC_PLAN_MAIN_ID = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_MAIN_ID"].ToString());
        TBL_ACC_PLAN_MAIN_planName = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_MAIN_planName"].ToString());
        TBL_ACC_PLAN_MAIN_maxLevel = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_MAIN_maxLevel"].ToString());
        TBL_ACC_PLAN_MAIN_format = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_MAIN_format"].ToString());
        TBL_ACC_PLAN_MAIN_transactionLevel = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_MAIN_transactionLevel"].ToString());
        TBL_ACC_PLAN_MAIN_isType = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_MAIN_isType"].ToString());
        TBL_ACC_PLAN_MAIN_areAllFixed = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_MAIN_areAllFixed"].ToString());
        TBL_ACC_PLAN_MAIN_areAllAutoGenerated = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_MAIN_areAllAutoGenerated"].ToString());
        TBL_ACC_PLAN_MAIN_leveSeperator = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_MAIN_leveSeperator"].ToString());
        TBL_ACC_PLAN_MAIN_description = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_MAIN_description"].ToString());
        TBL_ACC_PLAN_MAIN_isActive = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_MAIN_isActive"].ToString());

        }

        }

        return ds;

        }
        
    }
}
