using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.IO;
using System.Data.SqlClient;
using System.Data;


namespace BLL.ACC_BLL
{
//     *****************************************************************************************************************************************************************
 
 
//                             Code Type:           Business Logic Layer
//                             Creation Date:       4/27/2014 8:28:53 PM
//                             Auther:              Muhammad Usman Raza Attari
//                             Developed By :       786 Software House 
 
 
//    *****************************************************************************************************************************************************************
 
  public   class cls_TBL_ACC_PLAN_DEF
    {
      DAL.DALCustome obj_dal = new DAL.DALCustome();
 
        public Boolean  gproperty_allocatoin = false;
 
        string ExeState = "";
 
        private  char  status  ;
 
        public  char  STATUS  
        {
              get { return status; }
              set {status = value ; }
        }


        private string cMP_ID = null;

       public string CMP_ID
        {
            get { return cMP_ID; }
            set { cMP_ID = value; }
        }
       private string bRC_ID = null;

       public string BRC_ID
        {
            get { return bRC_ID; }
            set { bRC_ID = value; }
        }

        private bool tBL_ACC_PLAN_MAIN_isDeleted = false;

        public bool TBL_ACC_PLAN_MAIN_isDeleted
        {
            get { return tBL_ACC_PLAN_MAIN_isDeleted; }
            set { tBL_ACC_PLAN_MAIN_isDeleted = value; }
        }

 
        private  int  tBL_ACC_PLAN_DEF_ID  = 0;
 
        public  int  TBL_ACC_PLAN_DEF_ID  
        {
              get { return tBL_ACC_PLAN_DEF_ID; }
              set {tBL_ACC_PLAN_DEF_ID = value ; }
        }
 
        private  int  tBL_ACC_PLAN_MAIN_ID  = 0;
 
        public  int  TBL_ACC_PLAN_MAIN_ID  
        {
              get { return tBL_ACC_PLAN_MAIN_ID; }
              set {tBL_ACC_PLAN_MAIN_ID = value ; }
        }
 
        private  int  tBL_ACC_PLAN_DEF_levelNo  = 0;
 
        public  int  TBL_ACC_PLAN_DEF_levelNo  
        {
              get { return tBL_ACC_PLAN_DEF_levelNo; }
              set {tBL_ACC_PLAN_DEF_levelNo = value ; }
        }
 
        private  string  tBL_ACC_PLAN_DEF_format  = string.Empty;
 
        public  string  TBL_ACC_PLAN_DEF_format  
        {
              get { return tBL_ACC_PLAN_DEF_format; }
              set {tBL_ACC_PLAN_DEF_format = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_DEF_isFixed  = true;
 
        public  bool  TBL_ACC_PLAN_DEF_isFixed  
        {
              get { return tBL_ACC_PLAN_DEF_isFixed; }
              set {tBL_ACC_PLAN_DEF_isFixed = value ; }
        }
 
        private  string  tBL_ACC_PLAN_DEF_fixedAcc  = string.Empty;
 
        public  string  TBL_ACC_PLAN_DEF_fixedAcc  
        {
              get { return tBL_ACC_PLAN_DEF_fixedAcc; }
              set {tBL_ACC_PLAN_DEF_fixedAcc = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_DEF_isAutoGenerated  = true;
 
        public  bool  TBL_ACC_PLAN_DEF_isAutoGenerated  
        {
              get { return tBL_ACC_PLAN_DEF_isAutoGenerated; }
              set {tBL_ACC_PLAN_DEF_isAutoGenerated = value ; }
        }
 
        private  int  tBL_ACC_PLAN_DEF_accTypePlan  = 0;
 
        public  int  TBL_ACC_PLAN_DEF_accTypePlan  
        {
              get { return tBL_ACC_PLAN_DEF_accTypePlan; }
              set {tBL_ACC_PLAN_DEF_accTypePlan = value ; }
        }
 
        private  int  tBL_ACC_PLAN_DEF_accValidationPlan  = 0;
 
        public  int  TBL_ACC_PLAN_DEF_accValidationPlan  
        {
              get { return tBL_ACC_PLAN_DEF_accValidationPlan; }
              set {tBL_ACC_PLAN_DEF_accValidationPlan = value ; }
        }
 
        private  int  tBL_ACC_PLAN_DEF_fixedType  = 0;
 
        public  int  TBL_ACC_PLAN_DEF_fixedType  
        {
              get { return tBL_ACC_PLAN_DEF_fixedType; }
              set {tBL_ACC_PLAN_DEF_fixedType = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_DEF_isTransaction  = true;
 
        public  bool  TBL_ACC_PLAN_DEF_isTransaction  
        {
              get { return tBL_ACC_PLAN_DEF_isTransaction; }
              set {tBL_ACC_PLAN_DEF_isTransaction = value ; }
        }
 
        private  bool  tBL_ACC_PLAN_DEF_isActive  = true;
 
        public  bool  TBL_ACC_PLAN_DEF_isActive  
        {
              get { return tBL_ACC_PLAN_DEF_isActive; }
              set {tBL_ACC_PLAN_DEF_isActive = value ; }
        }
 
        public string insertion()
        {

              SqlParameter[] sql_param = new SqlParameter[14];
 
 
        sql_param[0] = new SqlParameter("@TBL_ACC_PLAN_MAIN_ID", SqlDbType.Int);
        sql_param[0].Value = TBL_ACC_PLAN_MAIN_ID ;
 
        sql_param[1] = new SqlParameter("@TBL_ACC_PLAN_DEF_levelNo", SqlDbType.Int);
        sql_param[1].Value = TBL_ACC_PLAN_DEF_levelNo ;
 
        sql_param[2] = new SqlParameter("@TBL_ACC_PLAN_DEF_format", SqlDbType.NVarChar);
        sql_param[2].Value = TBL_ACC_PLAN_DEF_format ;
 
        sql_param[3] = new SqlParameter("@TBL_ACC_PLAN_DEF_isFixed", SqlDbType.Bit);
        sql_param[3].Value = TBL_ACC_PLAN_DEF_isFixed ;
 
        sql_param[4] = new SqlParameter("@TBL_ACC_PLAN_DEF_fixedAcc", SqlDbType.NVarChar);
        sql_param[4].Value = TBL_ACC_PLAN_DEF_fixedAcc ;
 
        sql_param[5] = new SqlParameter("@TBL_ACC_PLAN_DEF_isAutoGenerated", SqlDbType.Bit);
        sql_param[5].Value = TBL_ACC_PLAN_DEF_isAutoGenerated ;
 
        sql_param[6] = new SqlParameter("@TBL_ACC_PLAN_DEF_accTypePlan", SqlDbType.Int);
        sql_param[6].Value = TBL_ACC_PLAN_DEF_accTypePlan ;
 
        sql_param[7] = new SqlParameter("@TBL_ACC_PLAN_DEF_accValidationPlan", SqlDbType.Int);
        sql_param[7].Value = TBL_ACC_PLAN_DEF_accValidationPlan ;
 
        sql_param[8] = new SqlParameter("@TBL_ACC_PLAN_DEF_fixedType", SqlDbType.Int);
        sql_param[8].Value = TBL_ACC_PLAN_DEF_fixedType ;
 
        sql_param[9] = new SqlParameter("@TBL_ACC_PLAN_DEF_isTransaction", SqlDbType.Bit);
        sql_param[9].Value = TBL_ACC_PLAN_DEF_isTransaction ;
 
        sql_param[10] = new SqlParameter("@TBL_ACC_PLAN_DEF_isActive", SqlDbType.Bit);
        sql_param[10].Value = TBL_ACC_PLAN_DEF_isActive ;

        sql_param[11] = new SqlParameter("@CMP_ID", SqlDbType.NVarChar);
        sql_param[11].Value = CMP_ID;

        sql_param[12] = new SqlParameter("@BRC_ID", SqlDbType.NVarChar);
        sql_param[12].Value = BRC_ID;

        sql_param[13] = new SqlParameter("@TBL_ACC_PLAN_MAIN_isDeleted", SqlDbType.Bit);
        sql_param[13].Value = TBL_ACC_PLAN_MAIN_isDeleted;





         ExeState = obj_dal.ins_del_upd("sp_TBL_ACC_PLAN_DEF_insertion", sql_param);

         return ExeState ;

        }
        
        
        
        
        
        public string updation()

        {

              SqlParameter[] sql_param = new SqlParameter[15];
 
        sql_param[0] = new SqlParameter("@TBL_ACC_PLAN_DEF_ID", SqlDbType.Int);
        sql_param[0].Value = TBL_ACC_PLAN_DEF_ID ;
 
        sql_param[1] = new SqlParameter("@TBL_ACC_PLAN_MAIN_ID", SqlDbType.Int);
        sql_param[1].Value = TBL_ACC_PLAN_MAIN_ID ;
 
        sql_param[2] = new SqlParameter("@TBL_ACC_PLAN_DEF_levelNo", SqlDbType.Int);
        sql_param[2].Value = TBL_ACC_PLAN_DEF_levelNo ;
 
        sql_param[3] = new SqlParameter("@TBL_ACC_PLAN_DEF_format", SqlDbType.NVarChar);
        sql_param[3].Value = TBL_ACC_PLAN_DEF_format ;
 
        sql_param[4] = new SqlParameter("@TBL_ACC_PLAN_DEF_isFixed", SqlDbType.Bit);
        sql_param[4].Value = TBL_ACC_PLAN_DEF_isFixed ;
 
        sql_param[5] = new SqlParameter("@TBL_ACC_PLAN_DEF_fixedAcc", SqlDbType.NVarChar);
        sql_param[5].Value = TBL_ACC_PLAN_DEF_fixedAcc ;
 
        sql_param[6] = new SqlParameter("@TBL_ACC_PLAN_DEF_isAutoGenerated", SqlDbType.Bit);
        sql_param[6].Value = TBL_ACC_PLAN_DEF_isAutoGenerated ;
 
        sql_param[7] = new SqlParameter("@TBL_ACC_PLAN_DEF_accTypePlan", SqlDbType.Int);
        sql_param[7].Value = TBL_ACC_PLAN_DEF_accTypePlan ;
 
        sql_param[8] = new SqlParameter("@TBL_ACC_PLAN_DEF_accValidationPlan", SqlDbType.Int);
        sql_param[8].Value = TBL_ACC_PLAN_DEF_accValidationPlan ;
 
        sql_param[9] = new SqlParameter("@TBL_ACC_PLAN_DEF_fixedType", SqlDbType.Int);
        sql_param[9].Value = TBL_ACC_PLAN_DEF_fixedType ;
 
        sql_param[10] = new SqlParameter("@TBL_ACC_PLAN_DEF_isTransaction", SqlDbType.Bit);
        sql_param[10].Value = TBL_ACC_PLAN_DEF_isTransaction ;
 
        sql_param[11] = new SqlParameter("@TBL_ACC_PLAN_DEF_isActive", SqlDbType.Bit);
        sql_param[11].Value = TBL_ACC_PLAN_DEF_isActive ;

        sql_param[12] = new SqlParameter("@CMP_ID", SqlDbType.NVarChar);
        sql_param[12].Value = CMP_ID;

        sql_param[13] = new SqlParameter("@BRC_ID", SqlDbType.NVarChar);
        sql_param[13].Value = BRC_ID;

        sql_param[14] = new SqlParameter("@TBL_ACC_PLAN_MAIN_isDeleted", SqlDbType.Bit);
        sql_param[14].Value = TBL_ACC_PLAN_MAIN_isDeleted;

        ExeState = obj_dal.ins_del_upd("sp_TBL_ACC_PLAN_DEF_updation", sql_param);

        return ExeState ; 
        }
        public string deletion()
        {

        SqlParameter[] sql_param = new SqlParameter[5];
 
        sql_param[0] = new SqlParameter("@STATUS", SqlDbType.Char);
        sql_param[0].Value = STATUS ;
        sql_param[2] = new SqlParameter("@TBL_ACC_PLAN_MAIN_ID", SqlDbType.Int);
        sql_param[2].Value = TBL_ACC_PLAN_MAIN_ID ;
        sql_param[3] = new SqlParameter("@CMP_ID", SqlDbType.NVarChar);
        sql_param[3].Value = CMP_ID;

        sql_param[4] = new SqlParameter("@BRC_ID", SqlDbType.NVarChar);
        sql_param[4].Value = BRC_ID;

        sql_param[5] = new SqlParameter("@TBL_ACC_PLAN_MAIN_isDeleted", SqlDbType.Bit);
        sql_param[5].Value = TBL_ACC_PLAN_MAIN_isDeleted;

 

         ExeState = obj_dal.ins_del_upd("sp_TBL_ACC_PLAN_DEF_deletion", sql_param);
        return ExeState ;

        }
        
        public DataSet selection()
        {

        SqlParameter[] sql_param = new SqlParameter[5];
 
        sql_param[0] = new SqlParameter("@STATUS", SqlDbType.Char);
        sql_param[0].Value = STATUS ;
        sql_param[2] = new SqlParameter("@TBL_ACC_PLAN_MAIN_ID", SqlDbType.Int);
        sql_param[2].Value = TBL_ACC_PLAN_MAIN_ID ;
        sql_param[3] = new SqlParameter("@CMP_ID", SqlDbType.NVarChar);
        sql_param[3].Value = CMP_ID;

        sql_param[4] = new SqlParameter("@BRC_ID", SqlDbType.NVarChar);
        sql_param[4].Value = BRC_ID;

        sql_param[5] = new SqlParameter("@TBL_ACC_PLAN_MAIN_isDeleted", SqlDbType.Bit);
        sql_param[5].Value = TBL_ACC_PLAN_MAIN_isDeleted;


        DataSet ds = new DataSet();

        ds = obj_dal.selection("sp_TBL_ACC_PLAN_DEF_selection", sql_param);

        if(ds == null)
        {
        return ds ;
        }

        int x = ds.Tables.Count;

         DataTable dt = new DataTable();

        dt = ds.Tables[0];

        if(gproperty_allocatoin == true)
        {
        if (dt.Rows.Count != 0)

        {

        TBL_ACC_PLAN_DEF_ID = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_DEF_ID"].ToString());
        TBL_ACC_PLAN_MAIN_ID = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_MAIN_ID"].ToString());
        TBL_ACC_PLAN_DEF_levelNo = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_DEF_levelNo"].ToString());
        TBL_ACC_PLAN_DEF_format = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_DEF_format"].ToString());
        TBL_ACC_PLAN_DEF_isFixed = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_DEF_isFixed"].ToString());
        TBL_ACC_PLAN_DEF_fixedAcc = Convert.ToString( dt.Rows[0]["TBL_ACC_PLAN_DEF_fixedAcc"].ToString());
        TBL_ACC_PLAN_DEF_isAutoGenerated = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_DEF_isAutoGenerated"].ToString());
        TBL_ACC_PLAN_DEF_accTypePlan = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_DEF_accTypePlan"].ToString());
        TBL_ACC_PLAN_DEF_accValidationPlan = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_DEF_accValidationPlan"].ToString());
        TBL_ACC_PLAN_DEF_fixedType = Convert.ToInt32( dt.Rows[0]["TBL_ACC_PLAN_DEF_fixedType"].ToString());
        TBL_ACC_PLAN_DEF_isTransaction = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_DEF_isTransaction"].ToString());
        TBL_ACC_PLAN_DEF_isActive = Convert.ToBoolean( dt.Rows[0]["TBL_ACC_PLAN_DEF_isActive"].ToString());

        }

        }

        return ds;

        }
        
    }
}
