using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.IO;
using System.Data.SqlClient;
using System.Data;


namespace BLL.ACC_BLL.TBL_ACC_PLAN
{

  public class cls_CTBL_ACC_PLAN_DEF
    {
       
     public static string priTBL_ACC_PLAN_DEF_ID = "TBL_ACC_PLAN_DEF_ID";
     public static string maxTBL_ACC_PLAN_DEF_ID = "TBL_ACC_PLAN_DEF_ID";
     
     public static string TBL_ACC_PLAN_MAIN_ID = "TBL_ACC_PLAN_MAIN_ID";
     public static string TBL_ACC_PLAN_DEF_levelNo = "TBL_ACC_PLAN_DEF_levelNo";
     public static string TBL_ACC_PLAN_DEF_format = "TBL_ACC_PLAN_DEF_format";
     public static string TBL_ACC_PLAN_DEF_isFixed = "TBL_ACC_PLAN_DEF_isFixed";
     public static string TBL_ACC_PLAN_DEF_fixedAcc = "TBL_ACC_PLAN_DEF_fixedAcc";
     public static string TBL_ACC_PLAN_DEF_isAutoGenerated = "TBL_ACC_PLAN_DEF_isAutoGenerated";
     public static string TBL_ACC_PLAN_DEF_accTypePlan = "TBL_ACC_PLAN_DEF_accTypePlan";
     public static string TBL_ACC_PLAN_DEF_accValidationPlan = "TBL_ACC_PLAN_DEF_accValidationPlan";
     public static string TBL_ACC_PLAN_DEF_fixedType = "TBL_ACC_PLAN_DEF_fixedType";
     public static string TBL_ACC_PLAN_DEF_isTransaction = "TBL_ACC_PLAN_DEF_isTransaction";
     public static string TBL_ACC_PLAN_DEF_isActive = "TBL_ACC_PLAN_DEF_isActive";
     public static string TBL_ACC_PLAN_DEF_isDeleted = "TBL_ACC_PLAN_DEF_isDeleted";


    }
}
