using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;

namespace PRESENTATION_LAYER.IMS_PRESENTATION_LAYER.Forms.TBL_CUSTOMERS
{
    public class cls_TBL_CUSTOMERS_P
    {

        Boolean isAllowedInsertion = true, 
              isAllowedUpdation = true, 
              isAllowedDeletion = true, 
          
              isDisturebedOnce = false, 
              isAutoGeneratedOption = false;




        GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;

        GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

        DATASET.IMS_DATASET.cls_DataSet obj_cls_DataSet_IMS = new DATASET.IMS_DATASET.cls_DataSet();

        GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

        BLL.IMS_BLL.TBL_CUSTOMERS.cls_TBL_CUSTOMERS obj_cls_TBL_CUSTOMERS = new BLL.IMS_BLL.TBL_CUSTOMERS.cls_TBL_CUSTOMERS();

        frm_TBL_CUSTOMERS obj_frm_TBL_CUSTOMERS = null;

        DataTable dt_Datanavigator = new DataTable();

        void InitializeComponents(frm_TBL_CUSTOMERS pobj_frm_TBL_CUSTOMERS, String pID)
        {

            obj_frm_TBL_CUSTOMERS = pobj_frm_TBL_CUSTOMERS;
            GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_CUSTOMERS, 'A');
            obj_cls_TBL_CUSTOMERS.obj_XtraForm = pobj_frm_TBL_CUSTOMERS;

            if (!obj_cls_TBL_CUSTOMERS.Open())
                obj_frm_TBL_CUSTOMERS.Close();



            if (pID == "N")
                Referesh("True");
            else
            {
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.Text = pID;

                selection("V", obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.Text.Trim());

            }

        }


        public cls_TBL_CUSTOMERS_P(frm_TBL_CUSTOMERS pobj_frm_TBL_CUSTOMERS, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, bool pIs_DisturbanceOnce)//VVVParamVVV
        {
            ObjGenForm = pObjGenForm;
            isDisturebedOnce = pIs_DisturbanceOnce;
            InitializeComponents(pobj_frm_TBL_CUSTOMERS, pID);

        }


        public bool validate(out string value, bool pIs_Delete)
        {
            if (pIs_Delete)
            {

                if (!isAllowedDeletion)
                {
                    value = obj_cls_MessageBox.error_delete_rights;
                    return false;

                }

                if (obj_frm_TBL_CUSTOMERS.DBStatus == 'I')
                {
                    value = obj_cls_MessageBox.error_selection_msg;
                    return false;
                }

            }
            else
            {
                if (obj_frm_TBL_CUSTOMERS.DBStatus == 'I')
                {
                    if (!isAllowedInsertion)
                    {
                        value = obj_cls_MessageBox.error_insert_rights;
                        return false;

                    }

                }
                if (obj_frm_TBL_CUSTOMERS.DBStatus == 'U')
                {
                    if (!isAllowedUpdation)
                    {
                        value = obj_cls_MessageBox.error_update_rights;
                        return false;

                    }

                }
 
       
                

                if (Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_name.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_Name_msg;
                    GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_name);
                    return false;
                }



                if (Convert.ToString(obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.EditValue) == "")
                {
                      value = obj_cls_MessageBox.error_Name_msg;
                      GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department);
                      return false;
                }
            

                //department
                if (Convert.ToString(obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.EditValue) == "")
                {
                    value = "First provide Department in order to perform action";
                    obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.Focus();
                    obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.Properties.AppearanceFocused.BorderColor = System.Drawing.Color.Red;
                    return false;
                }


              
               

            
            }

            if (obj_frm_TBL_CUSTOMERS.DBStatus == 'U')
                if (Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }
            if (obj_frm_TBL_CUSTOMERS.DBStatus == 'I')
                if (!obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.EditValue) == "")
                {
                    value = obj_cls_MessageBox.error_ID_msg;
                    return false;
                }


            value = "N";
            return true;
        }




        public void getMax()
        {
            if (obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Checked)
            {

                int tempID = obj_cls_DataSet_IMS.f_GETMAX("TBL_CUSTOMERS", 0, 0, 0, "", "", "");
                obj_frm_TBL_CUSTOMERS.maxID = tempID.ToString();
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.Text = obj_frm_TBL_CUSTOMERS.maxID;

            }
        }



        public void loadGridLookUpEdit(string Status)
        {

                    if (Status == "TBL_VEHICLE_MAKERS")
                        IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_VEHICLE_MAKERS(obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_vehicleMaker);

                    if (Status == "TBL_DEPARTMENTS")
                          IMS_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_DEPARTMENTSParent(obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department,false);

        }

        public string valueGetting(bool pIs_Delete)
        {

            try
            {

                string validate_value = "";

                if (!validate(out validate_value, pIs_Delete))
                {

                    if (validate_value == "N")
                        return "V_P";
                    else
                        return validate_value;

                }

                if (pIs_Delete)
                {
                    obj_cls_TBL_CUSTOMERS.STATUS      = "D";
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_ID = Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.EditValue);
                }
                {

                    obj_cls_TBL_CUSTOMERS.Is_Auto_Generated = obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Checked;

                    if (obj_frm_TBL_CUSTOMERS.DBStatus == 'I')
                    {

                        if (!obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Checked)
                            obj_cls_TBL_CUSTOMERS.CUSTOMER_ID = Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.EditValue);
                    }
                    else
                        obj_cls_TBL_CUSTOMERS.CUSTOMER_ID = Convert.ToString(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.EditValue);


                    obj_cls_TBL_CUSTOMERS.CUSTOMER_name         = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_name.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_address      = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_address.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_vehicleMaker = obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_vehicleMaker.EditValue  == null ? "0" : obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_vehicleMaker.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_department   = obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_vehicleNo    = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_vehicleNo.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_millage      = Convert.ToDecimal(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_millage.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_millage.EditValue.ToString().Trim());
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_year         = obj_frm_TBL_CUSTOMERS.ComboBoxEdit_CUSTOMER_year.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_creditLimit  = Convert.ToDecimal(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditLimit.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditLimit.EditValue.ToString().Trim());
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_creditDays   = Convert.ToDecimal(obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditDays.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditDays.EditValue.ToString().Trim());
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_phone        = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_phone.EditValue.ToString().Trim();
                    obj_cls_TBL_CUSTOMERS.CUSTOMER_email        = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_email.EditValue.ToString().Trim();


                }



            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }
        public string valueSetting(DataSet ds)
        {

            try
            {

                DataTable dt_Main = ds.Tables[0];

                obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_name.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_name];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_address.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_address];
                obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_vehicleMaker.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_vehicleMaker];
                obj_frm_TBL_CUSTOMERS.GridLookUpEdit_CUSTOMER_department.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_department];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_vehicleNo.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_vehicleNo];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_millage.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_millage];
                obj_frm_TBL_CUSTOMERS.ComboBoxEdit_CUSTOMER_year.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_year];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditLimit.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_creditLimit];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_creditDays.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_creditDays];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_phone.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_phone];
                obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_email.EditValue = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_email];
                obj_cls_TBL_CUSTOMERS.CUSTOMER_COA = dt_Main.Rows[0][BLL.IMS_BLL.TBL_CUSTOMERS.cls_CTBL_CUSTOMERS.CUSTOMER_COA].ToString();
                obj_frm_TBL_CUSTOMERS.DBStatus = 'U';
                obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Enabled = false;
            }
            catch (Exception ex)
            {

                return ex.Message;

            }

            return "ok";

        }


        public void Referesh(String isComplete)
        {

            if (isComplete == "True")
            {

                //try
                //{
                //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                //    foreach (DataRow d in drr)
                //    {
                //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                //        {
                //            isAllowedDeletion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                //        {
                //            isAllowedInsertion = true;
                //        }
                //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                //        {
                //            isAllowedUpdation = true;
                //        }
                //    }

                //}
                //catch (Exception ex)
                //{
                //    //throw;
                //}



                loadGridLookUpEdit("TBL_VEHICLE_MAKERS");
                loadGridLookUpEdit("TBL_DEPARTMENTS");

                obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                if (!isAllowedInsertion && !isAllowedUpdation)
                    obj_frm_TBL_CUSTOMERS.SimpleButton_Save.Enabled = false;
                if (!isAllowedDeletion)
                    obj_frm_TBL_CUSTOMERS.SimpleButton_Delete.Enabled = false;

                selection("N", "");
                Referesh("False");

            }
            else if (isComplete == "Partial")
            {
                selection("N", "");
                Referesh("False");

            }


            ObjGenForm.GenRefresh();
            obj_frm_TBL_CUSTOMERS.DBStatus = 'I';
            obj_frm_TBL_CUSTOMERS.CheckEdit_Is_AutoGenegereted.Enabled = true;
            //obj_frm_TBL_CUSTOMERS.CheckEdit_navigate.Checked = false;
            getMax();

        }

        public void Delete()
        {

            string executeFunctions = valueGetting(true);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }


            if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
            {

                return;

            }





            obj_cls_TBL_CUSTOMERS.CUSTOMER_ID = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.Text;

            if (obj_cls_TBL_CUSTOMERS.deletion())
            {
                Referesh("Partial");
                if (isDisturebedOnce)
                    obj_frm_TBL_CUSTOMERS.Close();
            }

        }

        public void Save()
        {


            string executeFunctions = valueGetting(false);

            if (executeFunctions != "ok")
            {
                if (executeFunctions != "N")
                {
                    if (executeFunctions == "V_P")
                    {
                        obj_cls_MessageBox.MessageBoxStatic("VP_E");
                        return;
                    }
                    else
                    {
                        obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                        return;

                    }
                }
            }

            if (obj_frm_TBL_CUSTOMERS.DBStatus == 'I')
            {   
               
                if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_CUSTOMERS.insertionUpdation('I'))
                {

                 



                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_CUSTOMERS.Close();
                }


            }

            else if (obj_frm_TBL_CUSTOMERS.DBStatus == 'U')
            {

                if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                {
                    return;
                }

                if (obj_cls_TBL_CUSTOMERS.insertionUpdation('U'))
                {
                    Referesh("Partial");
                    if (isDisturebedOnce)
                        obj_frm_TBL_CUSTOMERS.Close();
                }
            }

        }

        public void selection(string pStatus, string pId)
        {

            if (pStatus == "N")
            {
                if (pId == "")
                {
                    obj_cls_DataSet_IMS.f_TBL_CUSTOMERS("L", pId);
                    DataSet ds = obj_cls_DataSet_IMS.g_TBL_CUSTOMERS;
                    if (ds == null)
                    {
                        obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                        Referesh("False");
                        return;

                    }

                    dt_Datanavigator = ds.Tables[0].Copy();
                    obj_frm_TBL_CUSTOMERS.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                }
                else
                {

                    string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][0].ToString();
                    selection("V", ID);
                }
            }
            else if (pStatus == "A")
            {

                obj_cls_DataSet_IMS.f_TBL_CUSTOMERS("A", pId);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_CUSTOMERS;

                if (ds == null)
                {
                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                    Referesh("False");
                    return;

                }


                obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150,150,150,150,150,150,150,150,150", 1);
                obj_frlLOOKUP.ShowDialog();
                string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                if (value != "")
                {
                    string[] cols_values = value.Split('|');
                    obj_frm_TBL_CUSTOMERS.CheckEdit_navigate.Checked = false;
                    selection("V", cols_values[0]);
                }

            }
            else
            {

                obj_frm_TBL_CUSTOMERS.maxID = obj_frm_TBL_CUSTOMERS.TextEdit_CUSTOMER_ID.Text = pId;
                obj_cls_DataSet_IMS.f_TBL_CUSTOMERS("V", pId);
                DataSet ds = obj_cls_DataSet_IMS.g_TBL_CUSTOMERS;
                string executeFunctions = "";

                if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                {
                    executeFunctions = valueSetting(ds);
                }
                else
                {

                    obj_cls_MessageBox.MessageBoxStatic("TB_E");
                    Referesh("False");
                    return;

                }


                if (executeFunctions != "ok")
                {
                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                    return;

                    Referesh("False");


                }


            }

        }



        //VVVGRIDINFOVVV



    }
}
