using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;
using BLL.GEN_BLL.TBL_CMP;


namespace PRESENTATION_LAYER.GEN_PRESENTATION_LAYER.Forms.TBL_CMP
{
      public class cls_TBL_CMP_P
      {

            Boolean isAllowedInsertion = true, isAllowedUpdation = true, isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;

            GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;

            GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

            DATASET.GEN_DATASET.cls_DataSet obj_cls_DataSet_GEN = new DATASET.GEN_DATASET.cls_DataSet();

            GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

            BLL.GEN_BLL.TBL_CMP.cls_TBL_CMP obj_cls_TBL_CMP = new BLL.GEN_BLL.TBL_CMP.cls_TBL_CMP();

            frm_TBL_CMP obj_frm_TBL_CMP = null;

            DataTable dt_Datanavigator = new DataTable();
            String TBL_USERS_ID = "";

            void InitializeComponents(frm_TBL_CMP pobj_frm_TBL_CMP, String pID)
            {

                  obj_frm_TBL_CMP = pobj_frm_TBL_CMP;
                  GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_CMP, 'A');
                  obj_cls_TBL_CMP.obj_XtraForm = pobj_frm_TBL_CMP;

                  if (!obj_cls_TBL_CMP.Open())
                        obj_frm_TBL_CMP.Close();



                  if (pID == "N")
                        Referesh("True");
                  else
                  {
                        obj_frm_TBL_CMP.TextEdit_CMP_maxID.Text = pID;

                        selection("V", obj_frm_TBL_CMP.TextEdit_CMP_maxID.Text.Trim());

                  }

            }


            public cls_TBL_CMP_P(frm_TBL_CMP pobj_frm_TBL_CMP, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, bool pIs_DisturbanceOnce)//VVVParamVVV
            {
                  ObjGenForm = pObjGenForm;
                  isDisturebedOnce = pIs_DisturbanceOnce;
                  InitializeComponents(pobj_frm_TBL_CMP, pID);

            }


            public bool validate(out string value, bool pIs_Delete)
            {
                  if (pIs_Delete)
                  {

                        if (!isAllowedDeletion)
                        {
                              value = obj_cls_MessageBox.error_delete_rights;
                              return false;

                        }

                        if (obj_frm_TBL_CMP.DBStatus == 'I')
                        {
                              value = obj_cls_MessageBox.error_selection_msg;
                              return false;
                        }

                  }
                  else
                  {
                        if (obj_frm_TBL_CMP.DBStatus == 'I')
                        {
                              if (!isAllowedInsertion)
                              {
                                    value = obj_cls_MessageBox.error_insert_rights;
                                    return false;

                              }

                        }
                        if (obj_frm_TBL_CMP.DBStatus == 'U')
                        {
                              if (!isAllowedUpdation)
                              {
                                    value = obj_cls_MessageBox.error_update_rights;
                                    return false;

                              }

                        }



                        if (Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_name.EditValue) == "")
                        {
                              GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CMP.TextEdit_CMP_name);
                              value = "V_P";
                              return false;
                        }
                        if (Convert.ToString(obj_frm_TBL_CMP.TextEdit_USERS_loginID.EditValue) == "")
                        {
                              GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CMP.TextEdit_USERS_loginID);
                              value = "V_P";
                              return false;
                        }
                        if (Convert.ToString(obj_frm_TBL_CMP.TextEdit_USERS_password.EditValue) == "")
                        {
                              GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CMP.TextEdit_USERS_password);
                              value = "V_P";
                              return false;
                        }
                        //if (Convert.ToString(obj_frm_TBL_CMP.GridLookUpEdit_CMP_adminUserID.EditValue) == "")
                        //{
                        //      GEN.GEN_GEN.GenericClasses.Appearance.cls_Appearance.applyFocusAppreanceTextEdit(obj_frm_TBL_CMP.GridLookUpEdit_CMP_adminUserID);
                        //      value = "V_P";
                        //      return false;
                        //}


                  }

                  if (obj_frm_TBL_CMP.DBStatus == 'U')
                        if (Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_maxID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }
                  if (obj_frm_TBL_CMP.DBStatus == 'I')
                        if (!obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_maxID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }


                  value = "N";
                  return true;
            }




            public void getMax()
            {
                  if (obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Checked)
                  {

                        int tempID = obj_cls_DataSet_GEN.f_GETMAX("TBL_CMP", 0, 0, 0, "", "", "");
                        obj_frm_TBL_CMP.maxID = tempID.ToString();
                        obj_frm_TBL_CMP.TextEdit_CMP_maxID.Text = obj_frm_TBL_CMP.maxID;

                  }
            }



            public void loadGridLookUpEdit(string Status)
            {


                  GEN_PRESENTATION_LAYER.cls_bindGridLookUpEdit.TBL_RIGHTS_MAIN(obj_frm_TBL_CMP.GridLookUpEdit_CMP_adminUserID);

            }

            public string valueGetting(bool pIs_Delete)
            {

                  try
                  {

                        string validate_value = "";

                        if (!validate(out validate_value, pIs_Delete))
                        {

                              if (validate_value == "N")
                                    return "V_P";
                              else
                                    return validate_value;

                        }

                        if (pIs_Delete)
                        {
                              obj_cls_TBL_CMP.STATUS = "D";
                              obj_cls_TBL_CMP.CMP_ID = Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_maxID.EditValue);
                        }
                        {

                              obj_cls_TBL_CMP.Is_Auto_Generated = obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Checked;

                              if (obj_frm_TBL_CMP.DBStatus == 'I')
                              {

                                    if (!obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Checked)
                                          obj_cls_TBL_CMP.CMP_ID = Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_maxID.EditValue);
                              }
                              else
                                    obj_cls_TBL_CMP.CMP_ID = Convert.ToString(obj_frm_TBL_CMP.TextEdit_CMP_maxID.EditValue);


                              obj_cls_TBL_CMP.CMP_name = obj_frm_TBL_CMP.TextEdit_CMP_name.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.CMP_address = obj_frm_TBL_CMP.TextEdit_CMP_address.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.CMP_adminUserID = "";//obj_frm_TBL_CMP.GridLookUpEdit_CMP_adminUserID.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.CMP_phoneNumber = obj_frm_TBL_CMP.TextEdit_CMP_phoneNumber.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.CMP_numberOfBranches = Convert.ToInt32(obj_frm_TBL_CMP.TextEdit_CMP_numberOfBranches.EditValue.ToString().Trim() == "" ? "0" : obj_frm_TBL_CMP.TextEdit_CMP_numberOfBranches.EditValue.ToString().Trim());
                              obj_cls_TBL_CMP.CMP_narration = obj_frm_TBL_CMP.TextEdit_CMP_narration.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.USERS_loginID = obj_frm_TBL_CMP.TextEdit_USERS_loginID.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.USERS_password = obj_frm_TBL_CMP.TextEdit_USERS_password.EditValue.ToString().Trim();
                              obj_cls_TBL_CMP.USERS_ID = TBL_USERS_ID;


                        }



                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }
            public string valueSetting(DataSet ds)
            {

                  try
                  {

                        DataTable dt_Main = ds.Tables[0];

                        obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                        obj_frm_TBL_CMP.TextEdit_CMP_name.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_name];
                        obj_frm_TBL_CMP.TextEdit_CMP_address.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_address];
                        obj_frm_TBL_CMP.GridLookUpEdit_CMP_adminUserID.EditValue = "";// dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_adminUserID];
                        obj_frm_TBL_CMP.TextEdit_CMP_phoneNumber.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_phoneNumber];
                        obj_frm_TBL_CMP.TextEdit_CMP_numberOfBranches.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_numberOfBranches];
                        obj_frm_TBL_CMP.TextEdit_CMP_narration.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_CMP.cls_CTBL_CMP.CMP_narration];
                        obj_frm_TBL_CMP.TextEdit_USERS_loginID.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_USERS.cls_CTBL_USERS.USERS_loginID];
                        obj_frm_TBL_CMP.TextEdit_USERS_password.EditValue = dt_Main.Rows[0][BLL.GEN_BLL.TBL_USERS.cls_CTBL_USERS.USERS_password];
                        TBL_USERS_ID = dt_Main.Rows[0][BLL.GEN_BLL.TBL_USERS.cls_CTBL_USERS.priUSERS_ID].ToString();

                        obj_frm_TBL_CMP.DBStatus = 'U';
                        obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Enabled = false;
                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }


            public void Referesh(String isComplete)
            {

                  if (isComplete == "True")
                  {

                        //try
                        //{
                        //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                        //    foreach (DataRow d in drr)
                        //    {
                        //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedDeletion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedInsertion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedUpdation = true;
                        //        }
                        //    }

                        //}
                        //catch (Exception ex)
                        //{
                        //    //throw;
                        //}



                       // loadGridLookUpEdit("TBL_RIGHTS_MAIN");

                        obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                        if (!isAllowedInsertion && !isAllowedUpdation)
                              obj_frm_TBL_CMP.SimpleButton_Save.Enabled = false;
                        if (!isAllowedDeletion)
                              obj_frm_TBL_CMP.SimpleButton_Delete.Enabled = false;

                        selection("N", "");
                        Referesh("False");

                  }
                  else if (isComplete == "Partial")
                  {
                        selection("N", "");
                        Referesh("False");

                  }


                  ObjGenForm.GenRefresh();
                  obj_frm_TBL_CMP.DBStatus = 'I';
                  obj_frm_TBL_CMP.CheckEdit_Is_AutoGenegereted.Enabled = true;
                  //obj_frm_TBL_CMP.CheckEdit_navigate.Checked = false;
                  getMax();

            }

            public void Delete()
            {

                  string executeFunctions = valueGetting(true);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }


                  if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
                  {

                        return;

                  }





                  obj_cls_TBL_CMP.CMP_ID = obj_frm_TBL_CMP.TextEdit_CMP_maxID.Text;

                  if (obj_cls_TBL_CMP.deletion())
                  {
                        Referesh("Partial");
                        if (isDisturebedOnce)
                              obj_frm_TBL_CMP.Close();
                  }

            }

            public void Save()
            {


                  string executeFunctions = valueGetting(false);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }

                  if (obj_frm_TBL_CMP.DBStatus == 'I')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                        {
                              return;
                        }

                        if (obj_cls_TBL_CMP.insertionUpdation('I'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_CMP.Close();
                        }


                  }

                  else if (obj_frm_TBL_CMP.DBStatus == 'U')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                        {
                              return;
                        }

                        if (obj_cls_TBL_CMP.insertionUpdation('U'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_CMP.Close();
                        }
                  }

            }

            public void selection(string pStatus, string pId)
            {

                  if (pStatus == "N")
                  {
                        if (pId == "")
                        {
                              obj_cls_DataSet_GEN.f_TBL_CMP("L", pId);
                              DataSet ds = obj_cls_DataSet_GEN.g_TBL_CMP;
                              if (ds == null)
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                                    Referesh("False");
                                    return;

                              }

                              dt_Datanavigator = ds.Tables[0].Copy();
                              obj_frm_TBL_CMP.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                        }
                        else
                        {

                              string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][cls_CTBL_CMP.priCMP_ID].ToString();
                              selection("V", ID);
                        }
                  }
                  else if (pStatus == "A")
                  {

                        obj_cls_DataSet_GEN.f_TBL_CMP("A", pId);
                        DataSet ds = obj_cls_DataSet_GEN.g_TBL_CMP;

                        if (ds == null)
                        {
                              obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                              Referesh("False");
                              return;

                        }


                        obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150,150,150,150", 1);
                        obj_frlLOOKUP.ShowDialog();
                        string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                        if (value != "")
                        {
                              string[] cols_values = value.Split('|');
                              obj_frm_TBL_CMP.CheckEdit_navigate.Checked = false;
                              selection("V", cols_values[0]);
                        }

                  }
                  else
                  {

                        obj_frm_TBL_CMP.maxID = obj_frm_TBL_CMP.TextEdit_CMP_maxID.Text = pId;
                        obj_cls_DataSet_GEN.f_TBL_CMP("V", pId);
                        DataSet ds = obj_cls_DataSet_GEN.g_TBL_CMP;
                        string executeFunctions = "";

                        if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                        {
                              executeFunctions = valueSetting(ds);
                        }
                        else
                        {

                              obj_cls_MessageBox.MessageBoxStatic("TB_E");
                              Referesh("False");
                              return;

                        }


                        if (executeFunctions != "ok")
                        {
                              obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                              return;

                              Referesh("False");


                        }


                  }

            }



            //VVVGRIDINFOVVV



      }
}
