using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.IO;
using System.Data.SqlClient;
using System.Data;
namespace PRESENTATION_LAYER.ACC_PRESENTATION_LAYER.GColumns
{

  public   class cls_CTBL_ACC_PLAN
    
    {
    
public static string TBL = "TBL_ACC_PLAN";

public static string TBL_ACC_PLAN_MAIN_ID = " TBL_ACC_PLAN_MAIN_ID";
public static string TBL_ACC_PLAN_MAIN_planName=" TBL_ACC_PLAN_MAIN_planName";
public static string TBL_ACC_PLAN_MAIN_maxLevel = " TBL_ACC_PLAN_MAIN_maxLevel";
public static string TBL_ACC_PLAN_MAIN_format=" TBL_ACC_PLAN_MAIN_format";
public static string TBL_ACC_PLAN_MAIN_transactionLevel = " TBL_ACC_PLAN_MAIN_transactionLevel";
public static string TBL_ACC_PLAN_MAIN_isType = " TBL_ACC_PLAN_MAIN_isType";
public static string TBL_ACC_PLAN_MAIN_areAllFixed = " TBL_ACC_PLAN_MAIN_areAllFixed";
public static string TBL_ACC_PLAN_MAIN_areAllAutoGenerated = " TBL_ACC_PLAN_MAIN_areAllAutoGenerated";
public static string TBL_ACC_PLAN_MAIN_leveSeperator=" TBL_ACC_PLAN_MAIN_leveSeperator";
public static string TBL_ACC_PLAN_MAIN_description=" TBL_ACC_PLAN_MAIN_description";
public static string TBL_ACC_PLAN_MAIN_isActive = " TBL_ACC_PLAN_MAIN_isActive";

}

}
