using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraEditors;
using System.Data;
using BLL.ACC_BLL.TBL_VCH_MAIN;

namespace PRESENTATION_LAYER.ACC_PRESENTATION_LAYER.Forms.TBL_VCH_MAIN
{
      public class cls_TBL_VCH_MAIN_P
      {

            Boolean isAllowedInsertion = true, isAllowedUpdation = true, isAllowedDeletion = true, isDisturebedOnce = false, isAutoGeneratedOption = false;

            GEN.GEN_GEN.GenericClasses.Form.Gen_Form ObjGenForm;
            GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView ObjGenGrid;



            GEN.GEN_GEN.GenericClasses.cls_MessageBox obj_cls_MessageBox = new GEN.GEN_GEN.GenericClasses.cls_MessageBox();

            DATASET.ACC_DATASET.cls_DataSet obj_cls_DataSet_ACC = new DATASET.ACC_DATASET.cls_DataSet();

            GEN.GEN_GEN.Look.frlLOOKUP obj_frlLOOKUP = null;

            BLL.ACC_BLL.TBL_VCH_MAIN.cls_TBL_VCH_MAIN obj_cls_TBL_VCH_MAIN = new BLL.ACC_BLL.TBL_VCH_MAIN.cls_TBL_VCH_MAIN();

            frm_TBL_VCH_MAIN obj_frm_TBL_VCH_MAIN = null;

            DataTable dt_Datanavigator = new DataTable();
            DataTable DT_dataTableForGrid = new DataTable();

            public string tmpVCHPrefix = "";

            void InitializeComponents(frm_TBL_VCH_MAIN pobj_frm_TBL_VCH_MAIN, String pID)
            {

                   obj_frm_TBL_VCH_MAIN = pobj_frm_TBL_VCH_MAIN;
                  GEN.GEN_GEN.GenericClasses.cls_CustomeForm.applyPropertiesOnXtraForm(obj_frm_TBL_VCH_MAIN, 'A');
                  obj_cls_TBL_VCH_MAIN.obj_XtraForm = pobj_frm_TBL_VCH_MAIN;

                  if (!obj_cls_TBL_VCH_MAIN.Open())
                        obj_frm_TBL_VCH_MAIN.Close();



                  if (pID == "N")
                        Referesh("True");
                  else
                  {
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text = pID;

                        selection("V", obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text.Trim());

                  }

            }


            public cls_TBL_VCH_MAIN_P(frm_TBL_VCH_MAIN pobj_frm_TBL_VCH_MAIN, String pID, GEN.GEN_GEN.GenericClasses.Form.Gen_Form pObjGenForm, GEN.GEN_GEN.GenericClasses.Grid.Gen_GridView pObjGenGrid, bool pIs_DisturbanceOnce, string PtmpVCHPrefix = "")//VVVParamVVV
            {


                  ObjGenForm = pObjGenForm;
                  ObjGenGrid = pObjGenGrid;
                  isDisturebedOnce = pIs_DisturbanceOnce;
                  tmpVCHPrefix = PtmpVCHPrefix;
                  InitializeComponents(pobj_frm_TBL_VCH_MAIN, pID);

                  if (tmpVCHPrefix == "CP" )
                  {
                        obj_frm_TBL_VCH_MAIN.Text =  "Cash Payment Voucher";
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_chequeNo.Visible = false;
                        obj_frm_TBL_VCH_MAIN.LabelControl_TextEdit_VCH_chequeNo.Visible = false;
                  }
                  else if (tmpVCHPrefix == "BP")
                  {
                        obj_frm_TBL_VCH_MAIN.Text = "Bank Payment Voucher";
                        
                  }
                  if (tmpVCHPrefix == "CR")
                  {
                        obj_frm_TBL_VCH_MAIN.Text = "Cash Receipt Voucher";
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_chequeNo.Visible = false;
                        obj_frm_TBL_VCH_MAIN.LabelControl_TextEdit_VCH_chequeNo.Visible = false;

                  }
                  else if (tmpVCHPrefix == "BR")
                  {
                        obj_frm_TBL_VCH_MAIN.Text = "Bank Receipt Voucher";

                  }
                  else if (tmpVCHPrefix == "GV")
                  {
                        obj_frm_TBL_VCH_MAIN.Text = "General";

                  }
                  else if (tmpVCHPrefix == "OB")
                  {
                        obj_frm_TBL_VCH_MAIN.Text = "Opening Balance";

                  }


                 
                  

            }


            public bool validate(out string value, bool pIs_Delete)
            {
                  if (pIs_Delete)
                  {

                        if (!isAllowedDeletion)
                        {
                              value = obj_cls_MessageBox.error_delete_rights;
                              return false;

                        }

                        if (obj_frm_TBL_VCH_MAIN.DBStatus == 'I')
                        {
                              value = obj_cls_MessageBox.error_selection_msg;
                              return false;
                        }

                  }
                  else
                  {
                        if (obj_frm_TBL_VCH_MAIN.DBStatus == 'I')
                        {
                              if (!isAllowedInsertion)
                              {
                                    value = obj_cls_MessageBox.error_insert_rights;
                                    return false;

                              }

                        }
                        if (obj_frm_TBL_VCH_MAIN.DBStatus == 'U')
                        {
                              if (!isAllowedUpdation)
                              {
                                    value = obj_cls_MessageBox.error_update_rights;
                                    return false;

                              }

                        }


                        double tmpDebit = Convert.ToDouble(obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_debit].SummaryItem.SummaryValue.ToString());
                        double tmpCredit = Convert.ToDouble(obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].SummaryItem.SummaryValue.ToString());
                        string tmpNumericFormat = obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].DisplayFormat.FormatString;
                        string tmpStrDebit = tmpDebit.ToString(tmpNumericFormat);
                        string tmpStrCredit = tmpCredit.ToString(tmpNumericFormat);


                        if (tmpStrDebit != tmpStrCredit)
                        {
                              value = obj_cls_MessageBox.error_debit_credit_not_equal;
                              return false;
                        }


                  }

                  if (obj_frm_TBL_VCH_MAIN.DBStatus == 'U')
                        if (Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }
                  if (obj_frm_TBL_VCH_MAIN.DBStatus == 'I')
                        if (!obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Checked && Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue) == "")
                        {
                              value = obj_cls_MessageBox.error_ID_msg;
                              return false;
                        }


                  value = "N";
                  return true;
            }




            public void getMax()
            {
                  if (obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                  {

                        int tempID = obj_cls_DataSet_ACC.f_GETMAX("TBL_VCH_MAIN", 0, 0, 0, tmpVCHPrefix, "", "");
                        
                        obj_frm_TBL_VCH_MAIN.maxID =  GEN.ACC_GEN.Generics.cls_GACCFunctions.getCompleteVCHCodeWithoutPrefix(tempID.ToString());
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text = obj_frm_TBL_VCH_MAIN.maxID;

                  }
            }



            public void loadGridLookUpEdit(string Status)
            {



            }

            public string valueGetting(bool pIs_Delete)
            {

                  try
                  {

                        string validate_value = "";

                        if (!validate(out validate_value, pIs_Delete))
                        {

                              if (validate_value == "N")
                                    return "V_P";
                              else
                                    return validate_value;

                        }

                        if (pIs_Delete)
                        {
                              obj_cls_TBL_VCH_MAIN.STATUS = "D";
                           //   obj_cls_TBL_VCH_MAIN.VCH_ID = Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue);
                        }
                        {
                              obj_cls_TBL_VCH_MAIN.dt_Detail = DT_dataTableForGrid;
                              obj_cls_TBL_VCH_MAIN.Is_Auto_Generated = obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Checked;

                              //if (obj_frm_TBL_VCH_MAIN.DBStatus == 'I')
                              //{

                              //      if (!obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Checked)
                              //            obj_cls_TBL_VCH_MAIN.VCH_ID = Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue);
                              //}
                              //else
                              //      obj_cls_TBL_VCH_MAIN.VCH_ID = Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue);


                              obj_cls_TBL_VCH_MAIN.VCH_ID =  GEN.ACC_GEN.Generics.cls_GACCFunctions.getCompleteVCHCodeWithPrefix(Convert.ToString(obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue),tmpVCHPrefix);

                              obj_cls_TBL_VCH_MAIN.VCH_narration = obj_frm_TBL_VCH_MAIN.TextEdit_VCH_narration.EditValue.ToString().Trim();
                              obj_cls_TBL_VCH_MAIN.VCH_prefix = tmpVCHPrefix;
                              obj_cls_TBL_VCH_MAIN.VCH_date = obj_frm_TBL_VCH_MAIN.DateEdit_VCH_date.DateTime.Date;
                              obj_cls_TBL_VCH_MAIN.VCH_reference = obj_frm_TBL_VCH_MAIN.TextEdit_VCH_reference.EditValue.ToString().Trim();
                              obj_cls_TBL_VCH_MAIN.VCH_chequeNo = obj_frm_TBL_VCH_MAIN.TextEdit_VCH_chequeNo.EditValue.ToString().Trim();
                             

                        }



                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }
            public string valueSetting(DataSet ds)
            {

                  try
                  {

                        DataTable dt_Main = ds.Tables[0];
                        DT_dataTableForGrid = ds.Tables[1].Copy();
                        initiateGrid(false);
                        obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Checked = (Boolean)dt_Main.Rows[0][GEN.GEN_GEN.GenericClasses.cls_GENGlobalClass.Is_Auto_Generated];



                        obj_frm_TBL_VCH_MAIN.maxID = obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text = GEN.ACC_GEN.Generics.cls_GACCFunctions.getCompleteVCHCodeWithoutPrefix(dt_Main.Rows[0][BLL.ACC_BLL.TBL_VCH_MAIN.cls_CTBL_VCH_MAIN.maxVCH_maxID].ToString());

                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_narration.EditValue = dt_Main.Rows[0][BLL.ACC_BLL.TBL_VCH_MAIN.cls_CTBL_VCH_MAIN.VCH_narration];
                        obj_frm_TBL_VCH_MAIN.DateEdit_VCH_date.EditValue = dt_Main.Rows[0][BLL.ACC_BLL.TBL_VCH_MAIN.cls_CTBL_VCH_MAIN.VCH_date];
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_reference.EditValue = dt_Main.Rows[0][BLL.ACC_BLL.TBL_VCH_MAIN.cls_CTBL_VCH_MAIN.VCH_reference];
                        obj_frm_TBL_VCH_MAIN.TextEdit_VCH_chequeNo.EditValue = dt_Main.Rows[0][BLL.ACC_BLL.TBL_VCH_MAIN.cls_CTBL_VCH_MAIN.VCH_chequeNo];
                      
                        obj_frm_TBL_VCH_MAIN.DBStatus = 'U';
                        obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = false;
                  }
                  catch (Exception ex)
                  {

                        return ex.Message;

                  }

                  return "ok";

            }


            public void Referesh(String isComplete)
            {

                  if (isComplete == "True")
                  {

                        //try
                        //{
                        //    //DataRow[] drr = MDIClassic.dtRightsButton.Select(" [Parent Key] = '" + obj_frm_TBL_PRODUCTS_2.Tag + "'");
                        //    foreach (DataRow d in drr)
                        //    {
                        //        if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_del == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedDeletion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_insert == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedInsertion = true;
                        //        }
                        //        else if (GEN.GEN_GEN.GenericClasses.UserRIghts.cls_RightsKeys.key_update == d["Primary Key"].ToString())
                        //        {
                        //            isAllowedUpdation = true;
                        //        }
                        //    }

                        //}
                        //catch (Exception ex)
                        //{
                        //    //throw;
                        //}




                        obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Visible = isAutoGeneratedOption;

                        if (!isAllowedInsertion && !isAllowedUpdation)
                              obj_frm_TBL_VCH_MAIN.SimpleButton_Save.Enabled = false;
                        if (!isAllowedDeletion)
                              obj_frm_TBL_VCH_MAIN.SimpleButton_Delete.Enabled = false;
                        initiateGrid(true);
                        selection("N", "");
                        Referesh("False");

                  }
                  else if (isComplete == "Partial")
                  {
                        selection("N", "");
                        Referesh("False");

                  }


                  ObjGenForm.GenRefresh();
                  obj_frm_TBL_VCH_MAIN.DBStatus = 'I';
                  obj_frm_TBL_VCH_MAIN.CheckEdit_Is_AutoGenegereted.Enabled = true;
                  //obj_frm_TBL_VCH_MAIN.CheckEdit_navigate.Checked = false;
                  getMax();
                  DT_dataTableForGrid.Rows.Clear();

            }

            public void Delete()
            {

                  string executeFunctions = valueGetting(true);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }


                  if (obj_cls_MessageBox.MessageBoxStatic("D_Q") == "no")
                  {

                        return;

                  }





                  obj_cls_TBL_VCH_MAIN.VCH_ID = tmpVCHPrefix + "-" + obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text;

                  if (obj_cls_TBL_VCH_MAIN.deletion())
                  {
                        Referesh("Partial");
                        if (isDisturebedOnce)
                              obj_frm_TBL_VCH_MAIN.Close();
                  }

            }

            public void Save()
            {


                  string executeFunctions = valueGetting(false);

                  if (executeFunctions != "ok")
                  {
                        if (executeFunctions != "N")
                        {
                              if (executeFunctions == "V_P")
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("VP_E");
                                    return;
                              }
                              else
                              {
                                    obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "I_E");
                                    return;

                              }
                        }
                  }

                  if (obj_frm_TBL_VCH_MAIN.DBStatus == 'I')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("I_Q") == "no")
                        {
                              return;
                        }







                        if (obj_cls_TBL_VCH_MAIN.insertionUpdation('I'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_VCH_MAIN.Close();
                        }


                  }

                  else if (obj_frm_TBL_VCH_MAIN.DBStatus == 'U')
                  {

                        if (obj_cls_MessageBox.MessageBoxStatic("U_Q") == "no")
                        {
                              return;
                        }

                        if (obj_cls_TBL_VCH_MAIN.insertionUpdation('U'))
                        {
                              Referesh("Partial");
                              if (isDisturebedOnce)
                                    obj_frm_TBL_VCH_MAIN.Close();
                        }
                  }

            }

        public void Print()
        {
            if (obj_frm_TBL_VCH_MAIN.DBStatus == 'U')
            {

                IMS_PRESENTATION_LAYER.Reports.Sales.SaleInvoice.DM.rpt_VCH_INVOICE obj_rpt_DETAIL_SALE_INVOICE_SMALL = new IMS_PRESENTATION_LAYER.Reports.Sales.SaleInvoice.DM.rpt_VCH_INVOICE(tmpVCHPrefix + '-' + obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.EditValue.ToString());
                DevExpress.XtraReports.UI.ReportPrintTool objt = new DevExpress.XtraReports.UI.ReportPrintTool(obj_rpt_DETAIL_SALE_INVOICE_SMALL);

                //if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Print")
                //    objt.Print();
                //else if (obj_frm_TBL_SALES_AND_RETURN_MAIN.RadioGroud_printOrPreview.EditValue == "Preview")
                objt.ShowPreview();
            }

        }
            public void selection(string pStatus, string pId)
            {

                  if (pStatus == "N")
                  {
                        if (pId == "")
                        {
                              obj_cls_DataSet_ACC.f_TBL_VCH_MAIN("L", pId,tmpVCHPrefix);
                              DataSet ds = obj_cls_DataSet_ACC.g_TBL_VCH_MAIN;
                              if (ds == null)
                              {
                                    obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                                    Referesh("False");
                                    return;

                              }

                              dt_Datanavigator = ds.Tables[0].Copy();
                              obj_frm_TBL_VCH_MAIN.DataNavigator_Navigate.DataSource = dt_Datanavigator;
                        }
                        else
                        {

                              string ID = dt_Datanavigator.Rows[Convert.ToInt32(pId)][cls_CTBL_VCH_MAIN.priVCH_ID].ToString();
                              selection("V", ID);
                        }
                  }
                  else if (pStatus == "A")
                  {

                        obj_cls_DataSet_ACC.f_TBL_VCH_MAIN("A", pId, tmpVCHPrefix);
                        DataSet ds = obj_cls_DataSet_ACC.g_TBL_VCH_MAIN;

                        if (ds == null)
                        {
                              obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                              Referesh("False");
                              return;

                        }


                        obj_frlLOOKUP = new GEN.GEN_GEN.Look.frlLOOKUP(ds, 4, true, "150,150,150,150,150,150,150,150,150", 1);
                        obj_frlLOOKUP.ShowDialog();
                        string value = GEN.GEN_GEN.Look.frlLOOKUP.value;
                        if (value != "")
                        {
                              string[] cols_values = value.Split('|');
                              obj_frm_TBL_VCH_MAIN.CheckEdit_navigate.Checked = false;
                              selection("V", cols_values[0]);
                        }

                  }
                  else if (pStatus == "G")
                  {
                        obj_cls_DataSet_ACC.f_TBL_VCH_MAIN("G", pId, tmpVCHPrefix);
                        DataSet ds = obj_cls_DataSet_ACC.g_TBL_VCH_MAIN;
                        if (ds == null)
                        {
                              obj_cls_MessageBox.MessageBoxStatic("BLL_E");
                              Referesh("False");
                              return;

                        }

                        DT_dataTableForGrid = ds.Tables[0].Copy();
                  }
                  else
                  {

                        //obj_frm_TBL_VCH_MAIN.maxID = obj_frm_TBL_VCH_MAIN.TextEdit_VCH_ID.Text = pId;
                        obj_cls_DataSet_ACC.f_TBL_VCH_MAIN("V", pId, tmpVCHPrefix);
                        DataSet ds = obj_cls_DataSet_ACC.g_TBL_VCH_MAIN;
                        string executeFunctions = "";

                        if (!GEN.GEN_GEN.GenericClasses.DataTables.cls_NativDataSet.checkIsNullIsNoTableIsTableEmpty(ds, 0))
                        {
                              executeFunctions = valueSetting(ds);
                        }
                        else
                        {

                              obj_cls_MessageBox.MessageBoxStatic("TB_E");
                              Referesh("False");
                              return;

                        }


                        if (executeFunctions != "ok")
                        {
                              obj_cls_MessageBox.MessageBoxDynamics(executeFunctions, "S_E");
                              return;

                              Referesh("False");


                        }


                  }

            }

            public void initiateGrid(bool isNew)
            {
                  if (isNew)
                        selection("G", "");
                  obj_frm_TBL_VCH_MAIN.GridControl_TBL_VCH_DETAILS.DataSource = DT_dataTableForGrid;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.PopulateColumns();

                  //GEN.GEN_GEN.GenericClasses.Grid.cls_GridAppearance.setAppearance(obj_frm_TBL_TEMP_MAIN.GridView_TBL_TEMP_DET, "I");


                  // A_VCH_DETAILS_COA

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.A_VCH_DETAILS_COA].Caption = "Accounts IDs";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.A_VCH_DETAILS_COA].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.A_VCH_DETAILS_COA].Width = 200;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.A_VCH_DETAILS_COA].Tag = "N|N|Y|N";
                  ACC_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_COA(
                        obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.A_VCH_DETAILS_COA]
                        , "L_Type_Transaction_Active"
                        , ACC_PRESENTATION_LAYER.GColumns.cls_CTBL_COA.COA_UID
                        );

                  // VCH_DETAILS_COA

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_COA].Caption = "Accounts Names";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_COA].OptionsColumn.FixedWidth = false;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_COA].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_COA].Tag = "N|N|Y|N";
                  ACC_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_COA(
                        obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_COA]
                        , "L_Type_Transaction_Active"
                        , ACC_PRESENTATION_LAYER.GColumns.cls_CTBL_COA.COA_Name
                        );


                  // VCH_DETAILS_remarks

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Caption = "Narration";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Tag = "N|N|N|N";



                  // VCH_DETAILS_referenceNo

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_referenceNo].Caption = "Departments";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_referenceNo].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_referenceNo].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_referenceNo].Tag = "N|N|N|N";
                  IMS_PRESENTATION_LAYER.cls_bindGridLookColumns.TBL_DEPARTMENTS(
                        obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_referenceNo]
                        );


                  // VCH_DETAILS_debit

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_debit].Caption = "Debit";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_debit].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_debit].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_debit].Tag = "N2|S|N|N";


                  // VCH_DETAILS_credit

                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].Caption = "Credit";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_credit].Tag = "N2|S|N|N";



                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Caption = "Narration";
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].OptionsColumn.FixedWidth = true;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Width = 100;
                  obj_frm_TBL_VCH_MAIN.GridView_TBL_VCH_DETAILS.Columns[cls_CTBL_VCH_MAIN.VCH_DETAILS_remarks].Tag = "N|N|N|N";



                  ObjGenGrid.Formatting();
            }


            //VVVGRIDINFOVVV



      }
}
